### ISSUE TITLE
type 'Future<dynamic>' is not a subtype of type 'Future<bool>'

### ISSUE THREAD

**Issue by kw2019ltd** [jhomlala/catcher#1]
hi
getting below and due to below getting duplicate mail also.

I/flutter (17288): Sending email...

E/flutter (17288): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:

E/flutter (17288): type 'Future<dynamic>' is not a subtype of type 'Future<bool>'

E/flutter (17288): #0 EmailHandler.handle (package:catcher/handlers/email_handler.dart:37:5)

E/flutter (17288): #1 Catcher.onActionConfirmed (package:catcher/catcher.dart:160:17)

E/flutter (17288): #2 SilentReportMode.requestAction (package:catcher/mode/silent_report_mode.dart:11:22)

E/flutter (17288): #3 Catcher._reportError (package:catcher/catcher.dart:79:16)

E/flutter (17288): #4 _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)

E/flutter (17288): #5 Catcher._reportError (package:catcher/catcher.dart:75:15)

E/flutter (17288): #6 Catcher.reportCheckedError (package:catcher/catcher.dart:72:5)

E/flutter (17288): #7 retrievePlantsPrice (package:plants_price_flutter_app/http/plants_price_http.dart:26:27)

E/flutter (17288): #8 _asyncErrorWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:84:45)

E/flutter (17288): #9 _RootZone.runBinary (dart:async/zone.dart:1384:54)

E/flutter (17288): #10 _FutureListener.handleError (dart:async/future_impl.dart:143:20)

E/flutter (17288): #11 Future._propagateToListeners.handleError (dart:async/future_impl.dart:654:47)

E/flutter (17288): #12 Future._propagateToListeners (dart:async/future_impl.dart:675:24)

E/flutter (17288): #13 Future._completeError (dart:async/future_impl.dart:494:5)

E/flutter (17288): #14 _SyncCompleter._completeError (dart:async/future_impl.dart:55:12)

E/flutter (17288): #15 _Completer.completeError (dart:async/future_impl.dart:27:5)

E/flutter (17288): #16 _AsyncAwaitCompleter.completeError (dart:async/runtime/libasync_patch.dart:40:18)

E/flutter (17288): #17 _withClient (package:http/http.dart)

E/flutter (17288): #18 _asyncErrorWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:84:45)

E/flutter (17288): #19 _RootZone.runBinary (dart:async/zone.dart:1384:54)

E/flutter (17288): #20 _FutureListener.handleError (dart:async/future_impl.dart:143:20)

E/flutter (17288): #21 Future._propagateToListeners.handleError (dart:async/future_impl.dart:654:47)

E/flutter (17288): #22 Future._propagateToListeners (dart:async/future_impl.dart:675:24)

E/flutter (17288): #23 Future._completeError (dart:async/future_impl.dart:494:5)

E/flutter (17288): #24 _SyncCompleter._completeError (dart:async/future_impl.dart:55:12)

E/flutter (17288): #25 _Completer.completeError (dart:async/future_impl.dart:27:5)

E/flutter (17288): #26 _AsyncAwaitCompleter.completeError (dart:async/runtime/libasync_patch.dart:40:18)

E/flutter (17288): #27 BaseClient._sendUnstreamed (package:http/src/base_client.dart)

E/flutter (17288): #28 _asyncErrorWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:84:45)

E/flutter (17288): #29 _RootZone.runBinary (dart:async/zone.dart:1384:54)

E/flutter (17288): #30 _FutureListener.handleError (dart:async/future_impl.dart:143:20)

E/flutter (17288): #31 Future._propagateToListeners.handleError (dart:async/future_impl.dart:654:47)

E/flutter (17288): #32 Future._propagateToListeners (dart:async/future_impl.dart:675:24)

E/flutter (17288): #33 Future._completeError (dart:async/future_impl.dart:494:5)

E/flutter (17288): #34 _SyncCompleter._completeError (dart:async/future_impl.dart:55:12)

E/flutter (17288): #35 _Completer.completeError (dart:async/future_impl.dart:27:5)

E/flutter (17288): #36 _AsyncAwaitCompleter.completeError.<anonymous closure> (dart:async/runtime/libasync_patch.dart:43:20)

E/flutter (17288): #37 _microtaskLoop (dart:async/schedule_microtask.dart:41:21)

E/flutter (17288): #38 _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)

Reloaded 7 of 616 libraries in 3,470ms.

I/flutter (17288): Sending status: true

**Comment by jhomlala** [comment]
Fixed in 0.0.6
