### ISSUE TITLE
choosing exception handler based on particular exception

### ISSUE THREAD

**Issue by ayushin** [jhomlala/catcher#10]
Hi,

Great package! Have you thought about adding a functionality to choose a handler based on the actual exception?

Let's say I want to catch all APIErorrs and display a toast to a user instead of crashing the app.

**Comment by jhomlala** [comment]
Hi! It's awesome idea. I will try add this feature soon. 👍

**Comment by ayushin** [comment]
well, i've just tried doing that with a custom ErrorHandler and that works, however the problem is that the catcher won't catch asynchronous exceptions thrown inside of bloc event handling - e.g. .dispatch()

i'm trying to find a well working architecture for centralised exception handling including the async api layer, but this seem to be a dead end too

**Comment by jhomlala** [comment]
Can you show example when Catcher won't catch exception?

**Comment by ayushin** [comment]
import 'package:flutter_bloc/flutter_bloc.dart';

...

_loginBloc.dispatch(LoginEntered(username: _username, password: _password));


---

blocks/login_bloc.dart:

class LoginBloc...
...

  @override
  Stream<LoginState> mapEventToState(LoginState currentState,
      LoginEvent event,) async* {

if(event is LoginEntered) {
    throw "You won't catch me";
}

**Comment by jhomlala** [comment]
You're using generator function. Code inside your mapEventToState will be called when you've use your Stream somewhere. Are you using Stream from mapEventToState method? 

Also add print log in your mapEventToState method, so you will know if exception is really throwed, i.e.:
`if(event is LoginEntered) {
print("Error throw");
throw "You won't catch me";
}`

**Comment by jhomlala** [comment]
Added explicit exception report handler map: https://github.com/jhomlala/catcher/blob/master/README.md#explicit-exception-report-handler-map

This feature is for your request.

**Comment by jhomlala** [comment]
If your error still occurs, please open new issue.

**Comment by SaravanarajaGITHUB** [comment]
> well, i've just tried doing that with a custom ErrorHandler and that works, however the problem is that the catcher won't catch asynchronous exceptions thrown inside of bloc event handling - e.g. .dispatch()
> 
> i'm trying to find a well working architecture for centralised exception handling including the async api layer, but this seem to be a dead end too

Facing the same issue Cather can't able to catch an async exception, which comes is flutter Unhandled exception, but I resolved this using by adding all the main code under runzone now the un_catcehd error will be caught in onError and will be sent to catcher reportCheckedError again.
