### ISSUE TITLE
Update FlutterToast

### ISSUE THREAD

**Issue by FallenRiteMonk** [jhomlala/catcher#100]
FlutterToast has undergone a major update and is now on Version 6.0.0.

The problem now is that it requires the buildcontext in order to be able to display a toast.

As far as I have seen from the code, there is currently no possibility to access the context from within a handler.
Otherwise I would have given a PR a try, but like this I would like to ask/discuss the prefered way of dealing with this would be.

I'll have a better look at the code and try to present a solution proposal if I can come up with one.

**Comment by jhomlala** [comment]
Let's wait for a few days until FlutterToast author will fix his last release:
https://github.com/ponnamkarthik/FlutterToast/issues/191

**Comment by jhomlala** [comment]
Fixed in 0.3.16.

**Comment by FallenRiteMonk** [comment]
@jhomlala Thanks
