### ISSUE TITLE
Async exceptions not caught / reported if WidgetsFlutterBinding.ensureInitialized() is called before Catcher

### ISSUE THREAD

**Issue by ubulife1** [jhomlala/catcher#108]
While integrated catcher into our application (great package btw), I found that due to our dependencies / setup, WidgetsFlutterBinding.ensureInitialized() must be called before Catcher.  As a result, it appears this causes Flutter to not report the exception via the runZonedGuarded error handler in _setupErrorHooks.  From what I can tell, WidgetsFlutterBinding.ensureInitialized() needs to be called in the same zone as runApp in order for the error reporting to work correctly.  I forked catcher and verified that if we could have the ability to pass a function in to Catcher which returns a Future<Widget> (and performs  our required setup within the Zone), then the async exceptions are caught / reported as expected.

Example of the main with the issue:
main() async {
  /// STEP 1. Create catcher configuration.
  /// Debug configuration with dialog report mode and console handler. It will show dialog and once user accepts it, error will be shown   /// in console.
  CatcherOptions debugOptions =
      CatcherOptions(DialogReportMode(), [ConsoleHandler()]);

  /// Release configuration. Same as above, but once user accepts dialog, user will be prompted to send email with crash to support.
  CatcherOptions releaseOptions = CatcherOptions(DialogReportMode(), [
    EmailManualHandler(["support@email.com"])
  ]);

  WidgetsFlutterBinding.ensureInitialized();
  /// STEP 2. Pass your root widget (MyApp) along with Catcher configuration:
  Catcher(MyApp(), debugConfig: debugOptions, releaseConfig: releaseOptions);
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      /// STEP 3. Add navigator key from Catcher. It will be used to navigate user to report page or to show dialog.
      navigatorKey: Catcher.navigatorKey,
      home: Scaffold(
          appBar: AppBar(
            title: const Text('Plugin example app'),
          ),
          body: ChildWidget()),
    );
  }
}

class ChildWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
        child: FlatButton(
            child: Text("Generate error"),
            onPressed: generateError,
            ));
  }

  generateError() async {
    throw "Test exception";
  }
}

My recommendation would be to allow an initialization function to Catcher while preserving the previous ability to pass in a widget (Just a recommendation though -  perhaps there is something I'm missing with how the ensureInitialized interacts with async error reporting).

**Comment by jhomlala** [comment]
Great idea! I've added ensureInitialized flag to Catcher constructor. Thanks for your tip!
Please upgrade Catcher to > 0.3.18
