### ISSUE TITLE
Change debugConfig/releaseConfig after calling Catcher

### ISSUE THREAD

**Issue by edwin-alvarez** [jhomlala/catcher#110]
is there any way we can add or remove or change CatcherOptions after calling the initial Catcher constructor.

I want to provide the users the option to enable or disable error report modes at run time.

Ex:
```
  static void setReportMode() {
    var stg = getInstance().getCurrentConfig();
    stg.reportMode = SilentReportMode();
  }
```

**Comment by jhomlala** [comment]
Please upgrade Catcher to v. 0.3.18. There's new updateConfig method: https://github.com/jhomlala/catcher/blob/master/example/lib/update_config_example.dart

**Comment by edwin-alvarez** [comment]
Tested today. Works like a charm.
