### ISSUE TITLE
[Bug] Sentry handler can not set release

### ISSUE THREAD

**Issue by stephane-skipr** [jhomlala/catcher#111]
**I would like to work with RELEASES in Sentry so that I can de-minify my dart file.**

I am in Flutter Web ([✓] Flutter (Channel beta, 1.21.0-9.2.pre, on Mac OS X 10.15.5 19F101,) 
with Catcher - 0.3.19 to handle errors and send them to Sentry.

I have tried to set the environmentAttributes in SentryClient but it is not taken into account - see ref in github.
```
final catcherProdOptions = CatcherOptions(SilentReportMode(), [
    //ToastHandler(),
    ConsoleHandler(),
    SentryHandler(
      SentryClient(
          dsn:'xxx',
          environmentAttributes: Event(release: '1.0.0')),
      //userContext:
    ),
  ]);
```

I think the problem may be coming from this code snippet. 
It should have had a condition that takes the Event "release" in the environmentAttributes of the SentryClient into account.

```
String _getApplicationVersion(Report report) {
    String applicationVersion = "";
    var applicationParameters = report.applicationParameters;
    if (applicationParameters.containsKey("appName")) {
      applicationVersion += applicationParameters["appName"];
    }
    if (applicationParameters.containsKey("version")) {
      applicationVersion += " ${applicationParameters["version"]}";
    }
    if (applicationVersion.isEmpty) {
      applicationVersion = "?";
    }
    return applicationVersion;
  }

  Event buildEvent(Report report, Map<String, dynamic> tags) {
    return Event(
        loggerName: "Catcher",
        serverName: "Catcher",
        release: _getApplicationVersion(report),
        environment: report.applicationParameters["environment"],
        message: "Error handled by Catcher",
        exception: report.error,
        stackTrace: report.stackTrace,
        level: SeverityLevel.error,
        culprit: "",
        tags: changeToSentryMap(tags),
        userContext: this.userContext);
  }`
````
https://github.com/jhomlala/catcher/blob/e7816ec492c5c55e90f0e557855d12116c68ed63/lib/handlers/sentry_handler.dart#L73

Thank you for your support.

**Comment by jhomlala** [comment]
Please check 0.3.20 version. I've added there customEnvironment and customRelease parameters for SentryHandler.
