### ISSUE TITLE
Avoid the usage of ^

### ISSUE THREAD

**Issue by aguitto** [jhomlala/catcher#113]
You use the ^ in the dependencies and it cause bugs and let your library unusable if one of them release an update with bugs.

By example, from today we can't use your lib cause "mailer" produce these errors:

Compiler message:
AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/mailer-3.2.0/lib/src/entities/address.dart:5:9: Error: Constructor is marked 'const' so all fields must be final.
  const Address([this.mailAddress, this.name]);
        ^
AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/mailer-3.2.0/lib/src/entities/address.dart:2:10: Context: Field isn't final, but constructor is 'const'.
  String name;
         ^
AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/mailer-3.2.0/lib/src/entities/address.dart:3:10: Context: Field isn't final, but constructor is 'const'.
  String mailAddress;
         ^

Compiler message:
AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/mailer-3.2.0/lib/src/entities/address.dart:5:9: Error: Constructor is marked 'const' so all fields must be final.
  const Address([this.mailAddress, this.name]);
        ^
AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/mailer-3.2.0/lib/src/entities/address.dart:2:10: Context: Field isn't final, but constructor is 'const'.
  String name;
         ^
AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/mailer-3.2.0/lib/src/entities/address.dart:3:10: Context: Field isn't final, but constructor is 'const'.
  String mailAddress;

**Comment by jhomlala** [comment]
Removing ^ from dependencies declaration will cause error:

```Package validation found the following potential issues:
* Your dependency on "xxx" should allow more than one version. 
```
I won't cange this. You should try using flutter pub upgrade command (this may solve your issue).
