### ISSUE TITLE
Failed assertion: !_debugLocked is not true when trying to use PageReportMode

### ISSUE THREAD

**Issue by aimanbaharum** [jhomlala/catcher#12]
Hi. I'm using 0.0.10 version of this library since it is the latest build before AndroidX changes. 

I received this error when trying to use **PageModeReport** in Catcher.

```
Dart Error: Unhandled exception:
E/flutter ( 2453): 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 1554 pos 12: '!_debugLocked': is not true.
```

**Steps to reproduce:**

1. Use `PageReportMode`
2. Try to return null on any button to produce an error
3. Exception will be thrown as per log below
 - Report Page doesn't seem to display
 - Still displaying the red page of errors on the app

Seems like the error was thrown due to when `Navigator.push` is called to display the new page.

Any idea how to fix this issue?

P/s: I have to use an old version of the library because my project is still below Android 28.

---

main.dart

```
void main() {
  ReportMode reportMode = PageReportMode(
    titleText: 'Crash Bandicoot',
    showStackTrace: true,
  );
  ConsoleHandler consoleHandler = ConsoleHandler(
    enableApplicationParameters: true,
    enableCustomParameters: true,
    enableStackTrace: true,
    enableDeviceParameters: true
  );
  CatcherOptions debugOptions = CatcherOptions(reportMode, [consoleHandler]);
  print("main.dart catcher debug");
  Catcher(MyApp(), debugConfig: debugOptions);
//  runApp(new MyApp());
}

class MyApp extends StatelessWidget {

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    final app = MaterialApp(
      title: 'My Big Project',
      theme: buildTheme(),
      navigatorKey: Catcher.navigatorKey,
      onGenerateRoute: AppRouter().router().generator,
    );
    return app;
  }
}
```

---

**Full error log:**

> E/flutter ( 2453): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter ( 2453): 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 1554 pos 12: '!_debugLocked': is not true.
E/flutter ( 2453): #0      _AssertionError._doThrowNew (dart:core/runtime/liberrors_patch.dart:40:39)
E/flutter ( 2453): #1      _AssertionError._throwNew (dart:core/runtime/liberrors_patch.dart:36:5)
E/flutter ( 2453): #2      NavigatorState.push (package:flutter/src/widgets/navigator.dart:1554:12)
E/flutter ( 2453): #3      Navigator.push (package:flutter/src/widgets/navigator.dart:923:34)
E/flutter ( 2453): #4      PageReportMode.requestAction (package:catcher/mode/page_report_mode.dart:25:15)
E/flutter ( 2453): #5      Catcher._reportError (package:catcher/core/catcher.dart:208:35)
E/flutter ( 2453): <asynchronous suspension>
E/flutter ( 2453): #6      Catcher._setupErrorHooks.<anonymous closure> (package:catcher/core/catcher.dart:113:13)
E/flutter ( 2453): <asynchronous suspension>
E/flutter ( 2453): #7      _rootRunBinary (dart:async/zone.dart:1148:13)
E/flutter ( 2453): #8      _RootZone.runBinary (dart:async/zone.dart:1385:12)
E/flutter ( 2453): #9      runZoned.<anonymous closure> (dart:async/zone.dart:1479:21)
E/flutter ( 2453): #10     _CustomZone.handleUncaughtError (dart:async/zone.dart:1003:19)
E/flutter ( 2453): #11     Future._propagateToListeners (dart:async/future_impl.dart:558:16)
E/flutter ( 2453): #12     Future._completeError (dart:async/future_impl.dart:494:5)
E/flutter ( 2453): #13     _SyncCompleter._completeError (dart:async/future_impl.dart:55:12)
E/flutter ( 2453): #14     _Completer.completeError (dart:async/future_impl.dart:27:5)
E/flutter ( 2453): #15     _AsyncAwaitCompleter.completeError (dart:async/runtime/libasync_patch.dart:40:18)
E/flutter ( 2453): #16     Catcher._setupErrorHooks.<anonymous closure> (package:catcher/core/catcher.dart)
E/flutter ( 2453): <asynchronous suspension>
E/flutter ( 2453): #17     FlutterError.reportError (package:flutter/src/foundation/assertions.dart:408:14)
E/flutter ( 2453): #18     _debugReportException (package:flutter/src/widgets/framework.dart:5000:16)
E/flutter ( 2453): #19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3724:35)
E/flutter ( 2453): #20     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
E/flutter ( 2453): #21     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
E/flutter ( 2453): #22     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
E/flutter ( 2453): #23     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
E/flutter ( 2453): #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter ( 2453): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter ( 2453): #26     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4643:32)
E/flutter ( 2453): #27     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4975:17)
E/flutter ( 2453): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
E/flutter ( 2453): #29     _TheatreElement.update (package:flutter/src/widgets/overlay.dart:507:16)
E/flutter ( 2453): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
E/flutter ( 2453): #31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
E/flutter ( 2453): #32     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
E/flutter ( 2453): #33     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2286:33)
E/flutter ( 2453): #34     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:676:20)
E/flutter ( 2453): #35     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
E/flutter ( 2453): #36     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
E/flutter ( 2453): #37     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
E/flutter ( 2453): #38     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
E/flutter ( 2453): #39     _rootRun (dart:async/zone.dart:1124:13)
E/flutter ( 2453): #40     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter ( 2453): #41     _CustomZone.runGuard
E/flutter ( 2453): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter ( 2453): 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 1554 pos 12: '!_debugLocked': is not true.
E/flutter ( 2453): #0      _AssertionError._doThrowNew (dart:core/runtime/liberrors_patch.dart:40:39)
E/flutter ( 2453): #1      _AssertionError._throwNew (dart:core/runtime/liberrors_patch.dart:36:5)
E/flutter ( 2453): #2      NavigatorState.push (package:flutter/src/widgets/navigator.dart:1554:12)
E/flutter ( 2453): #3      Navigator.push (package:flutter/src/widgets/navigator.dart:923:34)
E/flutter ( 2453): #4      PageReportMode.requestAction (package:catcher/mode/page_report_mode.dart:25:15)
E/flutter ( 2453): #5      Catcher._reportError (package:catcher/core/catcher.dart:208:35)
E/flutter ( 2453): <asynchronous suspension>
E/flutter ( 2453): #6      Catcher._setupErrorHooks.<anonymous closure> (package:catcher/core/catcher.dart:113:13)
E/flutter ( 2453): <asynchronous suspension>
E/flutter ( 2453): #7      _rootRunBinary (dart:async/zone.dart:1148:13)
E/flutter ( 2453): #8      _RootZone.runBinary (dart:async/zone.dart:1385:12)
E/flutter ( 2453): #9      runZoned.<anonymous closure> (dart:async/zone.dart:1479:21)
E/flutter ( 2453): #10     _CustomZone.handleUncaughtError (dart:async/zone.dart:1003:19)
E/flutter ( 2453): #11     Future._propagateToListeners (dart:async/future_impl.dart:558:16)
E/flutter ( 2453): #12     Future._completeError (dart:async/future_impl.dart:494:5)
E/flutter ( 2453): #13     _SyncCompleter._completeError (dart:async/future_impl.dart:55:12)
E/flutter ( 2453): #14     _Completer.completeError (dart:async/future_impl.dart:27:5)
E/flutter ( 2453): #15     _AsyncAwaitCompleter.completeError (dart:async/runtime/libasync_patch.dart:40:18)
E/flutter ( 2453): #16     Catcher._setupErrorHooks.<anonymous closure> (package:catcher/core/catcher.dart)
E/flutter ( 2453): <asynchronous suspension>
E/flutter ( 2453): #17     FlutterError.reportError (package:flutter/src/foundation/assertions.dart:408:14)
E/flutter ( 2453): #18     _debugReportException (package:flutter/src/widgets/framework.dart:5000:16)
E/flutter ( 2453): #19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3724:35)
E/flutter ( 2453): #20     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
E/flutter ( 2453): #21     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
E/flutter ( 2453): #22     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
E/flutter ( 2453): #23     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
E/flutter ( 2453): #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter ( 2453): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter ( 2453): #26     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
E/flutter ( 2453): #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter ( 2453): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter ( 2453): #29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
E/flutter ( 2453): #30     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
E/flutter ( 2453): #31     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
E/flutter ( 2453): #32     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
E/flutter ( 2453): #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter ( 2453): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter ( 2453): #35     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
E/flutter ( 2453): #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter ( 2453): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter ( 2453): #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
E/flutter ( 2453): #39     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
E/flutter ( 2453): #40     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
E/flutter ( 2453): #41     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
E/flutter ( 2453): #42     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
E/flutter ( 2453): #43     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter ( 2453): #44     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter ( 2453): #45     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
E/flutter ( 2453): #46     Element.rebuil

**Comment by aimanbaharum** [comment]
Never mind, I think I got it working now. It was due to the way I throwing the exception. I mislooked at the code where I implement the `return null` statement. Turns out the button is already using `MaterialPageRoute`. Perhaps it conflicted with the `navigatorKey` from the main which invokes the same `MaterialPageRoute` to display the error page report.

... I don't know. I'm so new to Flutter navigation system. :man_shrugging:

**Comment by aimanbaharum** [comment]
Had to reopen this issue since the same exception is still there even though producing different throwable event than the `MaterialPageRoute`.

**Comment by jhomlala** [comment]
Why don't you use AndroidX libs, even if it's recommended by Google? If you're creating new project, you should target the highest SDK version as possible. Plenty of Flutter libs are using AndroidX now.

**Comment by kleinpetr** [comment]
Hey I have the same problem

  ```
CatcherOptions debugOptions =
      CatcherOptions(DialogReportMode(), [ConsoleHandler()]);
  CatcherOptions releaseOptions = CatcherOptions(DialogReportMode(), [
    EmailManualHandler(["info@example.com"])
  ]);

  Catcher(App(),
      debugConfig: debugOptions, releaseConfig: releaseOptions);
```

```
child: MaterialApp(
        debugShowCheckedModeBanner: false,
        title: 'Bazzarro',
        initialRoute: Routes.home, //default
        navigatorKey: Catcher.navigatorKey,
        onGenerateRoute: (RouteSettings settings) {
          switch (settings.name) {
            case Routes.home:
              return SimplePageRoute(builder: (context) => HomeScreen());
              break;
            case Routes.contacts:
              return SimplePageRoute(builder: (context) => ContactsScreen());
              break;
          }

          //*else
          return MaterialPageRoute(
              builder: (context) => NotFoundScreen(routeName: settings.name));
        },
      ),
```

I have got
```
E/flutter (21714): #1      _AssertionError._throwNew  (dart:core-patch/errors_patch.dart:36:5)
E/flutter (21714): #2      NavigatorState.push 
package:flutter/…/widgets/navigator.dart:1736
E/flutter (21714): #3      showGeneralDialog 
package:flutter/…/widgets/routes.dart:1558
E/flutter (21714): #4      showDialog 
package:flutter/…/material/dialog.dart:705
E/flutter (21714): #5      DialogReportMode._showDialog 
package:catcher/mode/dialog_report_mode.dart:12
E/flutter (21714): #6      DialogReportMode.requestAction 
package:catcher/mode/dialog_report_mode.dart:8
E/flutter (21714): #7      Catcher._reportError 
package:catcher/core/catcher.dart:264
E/flutter (21714): <asynchronous suspension>
E/flutter (21714): #8      Catcher._setupErrorHooks.<anonymous closure> 
package:catcher/core/catcher.dart:117
E/flutter (21714): <asynchronous suspension>
E/flutter (21714): #9      _rootRunBinary  (dart:async/zone.dart:1148:13)
E/flutter (21714): #10     _CustomZone.runBinary  (dart:async/zone.dart:1037:19)
E/flutter (21714): #11     runZoned.<anonymous closure>  (dart:async/zone.dart:1479:21)
E/flutter (21714): #12     _CustomZone.handleUncaughtError  (dart:async/zone.dart:1003:19)
E/flutter (21714): #13     Future._propagateToListeners  (dart:async/future_impl.dart:555:16)
E/flutter (21714): #14     Future._completeError  (dart:async/future_impl.dart:491:5)
E/flutter (21714): #15     _SyncCompleter._completeError  (dart:async/future_impl.dart:55:12)
E/flutter (21714): #16     _Completer.completeError  (dart:async/future_impl.dart:27:5)
E/flutter (21714): #17     _AsyncAwaitCompleter.completeError  (dart:async-patch/async_patch.dart:40:18)
E/flutter (21714): #18     Catcher._setupErrorHooks.<anonymous closure> (package:catcher/core/catcher.dart)
E/flutter (21714): <asynchronous suspension>
E/flutter (21714): #19     FlutterError.reportError 
package:flutter/…/foundation/assertions.dart:413
E/flutter (21714): #20     _debugReportException 
package:flutter/…/widgets/framework.dart:5017
E/flutter (21714): #21     ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:3742
E/flutter (21714): #22     Element.rebuild 
package:flutter/…/widgets/framework.dart:3565
E/flutter (21714): #23     ComponentElement._firstBuild 
package:flutter/…/widgets/framework.dart:3722
E/flutter (21714): #24     StatefulElement._firstBuild 
package:flutter/…/widgets/framework.dart:3864
E/flutter (21714): #25     ComponentElement.mount 
package:flutter/…/widgets/framework.dart:3717
E/flutter (21714): #26     Element.inflateWidget 
package:flutter/…/widgets/framework.dart:2961
E/flutter (21714): #27     Element.updateChild 
package:flutter/…/widgets/framework.dart:2764
E/flutter (21714): #28     SingleChildRenderObjectElement.mount 
package:flutter/…/widgets/framework.dart:4876
E/flutter (21714): #29     Element.inflateWidget 
package:flutter/…/widgets/framework.dart:2961
E/flutter (21714): #30     Element.updateChild 
package:flutter/…/widgets/framework.dart:2764
E/flutter (21714): #31     ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:3750
E/flutter (21714): #32     Element.rebuild 
package:flutter/…/widgets/framework.dart:3565
E/flutter (21714): #33     ComponentElement._firstBuild 
package:flutter/…/widgets/framework.dart:3722
E/flutter (21714): #34     ComponentElement.mount 
package:flutter/…/widgets/framework.dart:3717
E/flutter (21714): #35     Element.inflateWidget 
package:flutter/…/widgets/framework.dart:2961
E/flutter (21714): #36     Element.updateChild 
package:flutter/…/widgets/framework.dart:2764
E/flutter (21714): #37     SingleChildRenderObjectElement.mount 
package:flutter/…/widgets/framework.dart:4876
E/flutter (21714): #38     Element.inflateWidget 
package:flutter/…/widgets/framework.dart:2961
E/flutter (21714): #39     Element.updateChild 
package:flutter/…/widgets/framework.dart:2764
E/flutter (21714): #40     ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:3750
E/flutter (21714): #41     Element.rebuild 
package:flutter/…/widgets/framework.dart:3565
E/flutter (21714): #42     ComponentElement._firstBuild 
package:flutter/…/widgets/framework.dart:3722
E/flutter (21714): #43     StatefulElement._firstBuild 
package:flutter/…/widgets/framework.dart:3864
E/flutter (21714): #44     ComponentElement.mount 
package:flutter/…/widgets/framework.dart:3717
E/flutter (21714): #45     Element.inflateWidget 
package:flutter/…/widgets/framework.dart:2961
E/flutter (21714): #46     Element.updateChild (package:flutter/src/widgets/f
```
And yes, I am using Android X and the highest version of plugins.

**Comment by robertodoering** [comment]
I can reproduce it with `catcher 0.1.4` and the `DialogReportMode` whenever I am trying to navigate to a new screen where an exception is thrown during the first build.

Here is an example app where the error occurs:
```dart
import 'package:catcher/catcher_plugin.dart';
import 'package:flutter/material.dart';

void main() {
  final debugOptions = CatcherOptions(DialogReportMode(), [
    ConsoleHandler(),
  ]);

  Catcher(
    MyApp(),
    debugConfig: debugOptions,
  );
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      navigatorKey: Catcher.navigatorKey,
      home: HomePage(),
    );
  }
}

class HomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Center(
        child: RaisedButton(
          child: Text("navigate"),
          onPressed: () {
            Navigator.of(context).pushReplacement(MaterialPageRoute(
              builder: (context) => CrashScreen(),
            ));
          },
        ),
      ),
    );
  }
}

class CrashScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    throw Exception();

    return Container();
  }
}
```

I assume the problem is that the dialog is trying to be shown in the same frame when the new screen is being built. A fix for that would be to simply make the `_showDialog` method in `dialog_report_mode.dart` asynchronous and adding a `await Future.delayed(Duration.zero);` to force the dialog to be shown one frame after the build method runs.

The same works for the `PageReportMode` by adding the await before the `Navigator.push`is being called.

I am not sure if this is the most elegant solution but it worked for me.
@jhomlala if you like I can create a PR with the fix.

**Comment by jhomlala** [comment]
Thank you @robertodoering for finding solution for this problem. I have fixed it in 0.1.5.

**Comment by yuio4235** [comment]
Still hit this issue on iOS 13.3 with flutter 1.12.13+hotfix1.5

`'package:flutter/src/widgets/navigator.dart': Failed assertion: line 2330 pos 12: '!_debugLocked': is not true.`

**Comment by conceptualben** [comment]
Thought of leaving a note here that may be useful for others experiencing this issue:

On my case the issue was I was navigating to a new route on a method called right on initialisation of my screen, waving a call with `await` right before the navigation solved things to me. (this was on was a startup screen that checked user and redirected accordingly)

**Comment by fsresponser** [comment]
the same thing. 
My solution is: WidgetsBinding.instance.addPostFrameCallback((_){}。 
I found it occurs when performing setState and navigate (probably Navigator.push, showDialog, showMenu etc) in the same time. So, i think we shouldn't perform actions that affect render process.

**Comment by flutterq2** [comment]
All Possible soution added [[Solved] Failed assertion: line ‘!_debugLocked’: I/flutter (24830): is not true](https://fluttercorner.com/error-thrown-on-navigator-pop-until-debuglocked-is-not-true/)
