### ISSUE TITLE
Open Telememtry

### ISSUE THREAD

**Issue by joe-getcouragenow** [jhomlala/catcher#121]
**Is your feature request related to a problem? Please describe.**

Open Telemetry is an open eco system, and so you can you run your own Telemetry Collector or use many of the SAAS Providers. The solves being trapped and also give you options. 

Its vendor agnostic. Here is one of the many self hosted servers: https://github.com/open-telemetry/opentelemetry-collector

I consider it the future way... 

**Describe the solution you'd like**

First we need to write an exporter for Flutter. Its not that hard because its ONLY PRoto and grpc, which is standard for Flutter.
Here is the Golang one: https://github.com/open-telemetry/opentelemetry-go/tree/master/exporters

**Describe alternatives you've considered**

Sentry works but only has basic things. you need logs, spans, metrics, and crashes with stack traces for a complete solution, and open telemetry can do all that.

**Additional context**

The Proto is the starting point: github.com/open-telemetry/opentelemetry-proto

I started the conversation with the team.

**Comment by jhomlala** [comment]
@joe-getcouragenow thanks for this idea, but I think creating collector of open telemetry is a subject for another package. 
If there will be open telemetry collector implemented in Dart, then I will add support for open telemetry in Catcher. Right now I don't have enough time to do that. Feel free to create collector in Dart and let me know :)
