### ISSUE TITLE
sentry_flutter

### ISSUE THREAD

**Issue by HudsonAfonso** [jhomlala/catcher#124]
use sentry_flutter: https://pub.dev/packages/sentry_flutter/changelog#400-beta1

Fix: StackTrace frames with 'package' uri.scheme are inApp by default #185
Fix: Missing App's StackTrace frames for Flutter errors
Enhancement: add isolateErrorIntegration and runZonedGuardedIntegration to default integrations in sentry-dart
Fix: Breadcrumb list is a plain list instead of a values list #201
Ref: Remove deprecated classes (Flutter Plugin for Android) and cleaning up #186
Fix: Handle immutable event lists and maps
Fix: NDK integration was being disabled by a typo
Fix: Missing toList for debug meta #192
Enhancement: NavigationObserver to record Breadcrumbs for navigation events #197
Fix: Integrations should be closeable
Feat: Support split-debug-info for Android #191
Fix: The event payload must never serialize null or empty fields
Ref: Make hints optional

**Comment by jhomlala** [comment]
@HudsonAfonso Could you elaborate? Catcher uses `sentry` package instead of `flutter_sentry`. And I'll upgrade `sentry` package version once new version will be stable.
