### ISSUE TITLE
On handled throw catcher dialog goes up, why?

### ISSUE THREAD

**Issue by tasibalint** [jhomlala/catcher#126]
I have a fetch method which throws an exception which is handled by a method which does stuff after the fetch is successfull, and the user is able to fetch manually by clicking a button which handles the fetch method and displays if an error happens. In short the error is handled, but the Catcher dialog pops up like my app is crashing which is wrong, and I don't understand why the catcher comes up. In Release and in Debug mode.

1. Button to fetch 
() {
  try {
   fetchList();
   setState((){});
  } catch (e) {
    SnackBar.showError(e.toString()); // <== a custom method to call a snackbar with color etc. none important it shows up with the catcher dialog
  }
}
2. fetchList() async {
   try {
   await ServiceListFetcher.fetch();
    sortList();
   } catch(e) {
     rethrow;
   }
}
3. class ServiceListFetcher {
   static fetch() async {
      try {
       http.Response response = await http.get(
        "url",
        headers:  {"Authorization": "Bearer xyz-stuff"});
      } catch (e) {
       throw HttpException(e);
      }
   }
}

I have struggels currently with exception handling in dart I dont know if I have to try catch every point where the error is able to travel or if it get automaticly handed over from child to parant method and I only need one try catch. Anyways I don't want to pop Catcher up with App is Crashing dialog even tho it isn't crashing because it is handled. Please elaborate what I m doing wrong.

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 1.24.0-2.0.pre.98, on Microsoft Windows [Version 10.0.18363.1198], locale en-AT)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] IntelliJ IDEA Ultimate Edition (version 2020.1)
[√] VS Code (version 1.51.1)
[√] Connected device (4 available)
• No issues found!

**Catcher version**
- Version: catcher: ^0.3.22

**Smartphone (please complete the following information):**
 - Device: Android Emulator Pixel 2 API 29
 - OS: Android 10.0

**Comment by jhomlala** [comment]
@tasibalint You're missing async/await in your first method:

```dart
  void someFun() async{
    try {
      await fetchList();
      setState(() {});
    } catch (e) {
      SnackBar.showError(e.toString());
    }
  }
```

Without this, your try/catch block won't work and Catcher will catch this error.

**Comment by subzero911** [comment]
@jhomlala in your handlers list you have Toast but don't have Snackbar.
How to show a snackbar on error?
