### ISSUE TITLE
[FEAUTRE] Add support for MacOS (after alpha)

### ISSUE THREAD

**Issue by moovida** [jhomlala/catcher#128]
**Describe the bug**
I am running my app on Macos, so this is only "kind of a bug". But a workaround would be great.

Basically all my exceptions are hidden by catcher, also if I set the debugConfig to null. I always get:
```
Instance of 'SilentReportMode' in not supported for Unknown platform
```

**To Reproduce**

Build for macos and trigger an exception.

**Expected behavior**

Well, I would love to have at least a fallback option to console. Something that would alreayd work for each platform.

**Screenshots**

**Flutter doctor**

[✓] Flutter (Channel dev, 1.25.0-4.0.pre, on macOS 11.0.1 20B29 darwin-x64, locale en-GB)
[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.51.1)

**Catcher version**

- Version: 0.3.23

**Comment by jhomlala** [comment]
MacOS is not yet supported. Probably it will be implemented, once MacOS support will be pushed out from alpha.

**Comment by Ephenodrom** [comment]
This would bei great. I am currently porting some APPs to MacOS and Linux. Would bei nice to usw this package there.

**Comment by jhomlala** [comment]
Added in 0.6.x release.
