### ISSUE TITLE
[FIX] better support for custom error messages on toast handler

### ISSUE THREAD

**Issue by fonstack** [jhomlala/catcher#135]
![CleanShot 2021-01-18 at 12 30 25](https://user-images.githubusercontent.com/35873992/104941120-08534a80-5989-11eb-9b20-ef238568f505.png)

If I don't send error, show custom message, but if I send message, show the message I sent without 'error occurred' because intl

**Comment by jhomlala** [comment]
Fixed in 0.4.1.
