### ISSUE TITLE
[FEATURE] Migrate to sound null safety 

### ISSUE THREAD

**Issue by LearningRaph** [jhomlala/catcher#139]
Migrate to sound null safety
Bump up package version

**Comment by SirusCodes** [comment]
Any updates on this?

**Comment by DanMossa** [comment]
Currently looking to use Catcher and would need this updated to support null-safety

**Comment by basti1253** [comment]
I was curious if I could just migrate it by now and open a PR. There's still one dependency that's not ready yet- sentry. https://github.com/getsentry/sentry-dart/issues/247

A partial upgrade fails therefore:
```bash
flutter pub upgrade --nullsafety flutter_mailer lint device_info package_info mailer fluttertoast logging dio
```

prints:

```
Because dio >=4.0.0-beta1 depends on http_parser ^4.0.0 and http >=0.11.3+17 <0.13.0-nullsafety.0 depends on http_parser >=0.0.1 <4.0.0, dio >=4.0.0-beta1 is incompatible with http >=0.11.3+17 <0.13.0-nullsafety.0.
And because sentry >=4.0.0-alpha.1 depends on http ^0.12.0, dio >=4.0.0-beta1 is incompatible with sentry >=4.0.0-alpha.1.
So, because catcher depends on both dio >=4.0.0-beta1 and sentry ^4.0.0, version solving failed.
pub finished with exit code 1
```

**Comment by jhomlala** [comment]
All dependecies need to be null-safety in order to update Catcher to null safety. I believe sentry will be updated soon and Catcher's null-safety process will be unblocked.

**Comment by jhomlala** [comment]
Nullsafety version of Sentry will be released next week. Until that, you may use Catcher's version without Sentry. Simply add this in pubspec.yaml:

```yaml
  catcher:
    git:
      url: https://github.com/jhomlala/catcher
      ref: feature/nullsafety
```

**Comment by jhomlala** [comment]
Catcher 0.5.0  with null safety has been released.
