### ISSUE TITLE
Split configuration from runApp

### ISSUE THREAD

**Issue by Simone999** [jhomlala/catcher#14]
There are situations where you have a lot of configuration before runApp and i think error handling must be the first thing should be configured. Having catcher built in this way doesn't let to catch errors before runApp.

**Comment by jhomlala** [comment]
Please see this experimental example: https://github.com/jhomlala/catcher/blob/feature/no_widget_init/example/lib/init_with_function_example.dart

As you can see, I've added new constructor Catcher.withFunction which allows you to setup other libraries before running root widget. Is this what are you looking for?

**Comment by Simone999** [comment]
Yes, that's a good solution, but i want to catch error from every type of function, not only from something that return a widget.
Do you think it's a bad idea having a common configuration point for release, development and profile? I think it could be better if we can simply use `Catcher.withFunction(function) `without passing configurations every time.
I mean something like
```
Catcher.configure({this.releaseConfig, this.debugConfig, this.profileConfig});

Catcher.withFunction(this._function,{this.releaseConfig, this.debugConfig, this.profileConfig});

Catcher.runApp(Widget rootApp, {this.releaseConfig, this.debugConfig, this.profileConfig});
```

Of course, report mode is ignored in `withFunction`.

**Comment by jhomlala** [comment]
From my perspective, your application should start with one of the method:

Catcher.withFunction()
Catcher.runApp()

So there is no point for specifing additional step for configuration. It will create confusion and devs won't know which method should be used to configure. Also I don't want to change API right now.

See updated example:
https://github.com/jhomlala/catcher/blob/feature/no_widget_init/example/lib/init_with_function_example.dart

As you can see init method can return anything. But you need to start app manually with runApp(widget).

**Comment by Simone999** [comment]
I have forked the project and added some changes (not tested, only for explaination purpose).
This is what i mean: [https://github.com/Simone999/catcher/blob/feature/no_widget_init/lib/core/catcher.dart](https://github.com/Simone999/catcher/blob/feature/no_widget_init/lib/core/catcher.dart)

I want to have a `withFunction` method because before the runningApp i configure database, logger, blocs and other stuff that I think should be configured before showing the app. In this way, while I'm configuring stuffs, the app show the splashScreen

**Comment by java-james** [comment]
+1 if you throw in your root widget  _setupReportMode(); hasn't been called yet so  _reportModeAction.onActionConfirmed(report); will fail (_reportModeAction is null as it hasn't been configured). Causing an unhandled exception.
