### ISSUE TITLE
[BUG] HTML escape in email auto/manual handler

### ISSUE THREAD

**Issue by narumishi** [jhomlala/catcher#142]
**Describe the bug**
Currently, all messages are written into html directly. For example, in error and stacktrace string, there are many `<>` closures which won't be displayed in email body. We can easily use `HTMLEscape().convert` to convert them.

Messages (may) need to be escaped:
- `error` & `stackTrace`, the most important
- **values** of device/application/custom parameters, in general, there is little unsafe code
- `emailHeader`: convert it or tell user it is a html string in api doc

**Comment by jhomlala** [comment]
Fixed in 0.6.2.
