### ISSUE TITLE
[QUESTION] Any plans to make private methods public?

### ISSUE THREAD

**Issue by narumishi** [jhomlala/catcher#143]
Recently, I use the `catcher` package to deal with errors, and found it is less customizable.

For example, I may need some extra operations or modifications when:
- before a handler start handling
  - add screenshot attachment when send email
- change **a few** behaviours of widget in dialog/page report mode
  - add error before stacktrace
- handle errors one-by-one in dialog/page report mode
  - if keep producing errors, infinite dialog will be pushed, and I can do nothing, it should be a bug. All `onActionConfirmed`, `onActionRejected` in catcher and `handle` in handlers should be async and handle error one-by-one. Exactly, the `_cachedReports` is never used in deed.
- desktop support
  - inside loading device and app info, some workflow like `if not web then we support`, `if not android else it is ios`, even not check `PlatformType.unknown`. Bug too.

I have to copy the whole file if any target above. Actually I clone  and modify the entire repo. It is expensive and hard to maintain.

Since now the package is in nullsafety migration, desktop support and make api public may affect most files or may against your principle, so I create such an issue to **discus**. If possible, I'm glad to contribute to the package.

**Comment by jhomlala** [comment]
@narumishi Thanks for these ideas.

Screenshots feature has been added in 0.6.2.
Desktop support has been added in 0.6.0.

Other ideas/problems - can you create issue/feature request separately? It would be helpful to provide some reproducible code/steps.

**Comment by narumishi** [comment]
@jhomlala thanks for your fix. I will create new issues later for the left points.
