### ISSUE TITLE
[FEATURE] Designated way to get reference to the catcher at runtime

### ISSUE THREAD

**Issue by timosturm** [jhomlala/catcher#144]
**Is your feature request related to a problem? Please describe.**
I want to update the releaseOption of the catcher when the application ist running. But the `updateConfig` method is not static, thus I need a reference to the Catcher object that wraps around my application.

**Describe the solution you'd like**
The catcher class hold a reference to the instantiated Catcher, but it is private: https://github.com/jhomlala/catcher/blob/23cf71a52c07c9754cc0279b94ad1329c14f930f/lib/core/catcher.dart#L23  Ideally this would be not and I could update the config by `Catcher.instance.updateConfig(...)`.

**Describe alternatives you've considered**
Currently I hold a reference to the catcher that I create in the main method, something like this:
```
Catcher catcher;

void main() async {
  // Setup of release / debug options
  catcher = Catcher(...)
  ...
}
```
This solution is not really practicable.

#### I made a pull request with the necessary changes -> https://github.com/jhomlala/catcher/pull/145

**Comment by jhomlala** [comment]
I don't understand,  why did you don't use DI or some other dependency pass within tree like bloc does? Or even just create on your app some simple singleton. There are many possibilites to handle this problem.

**Comment by timosturm** [comment]
To give an answer I want to elaborate:
I haven't used dependency injection in flutter before, but I am familiar with the `Class.of(context)` syntax that most other plugins seem to use and `Catcher.instance` is very similar to that. This is why it felt natural for me to use that syntax here.

Also this is a rather small change that provides all functionality that I need, thus it feels like the best way to do it.

**Comment by jhomlala** [comment]
Added getInstance method in Catcher class in 0.6.2 version.
