### ISSUE TITLE
[Question] Stacktrace and --obfuscation when building release

### ISSUE THREAD

**Issue by djsliders** [jhomlala/catcher#146]
Hi,

Thank you for the project.
I juse have one question: If I use the obfuscation when building the release, all my exceptions stacktrace are not usable to debug.

Do we have a way to use the mapping file generated at the build time to Catcher so we can have a readable stacktrace?

Thank you

**Comment by jhomlala** [comment]
I think it's not doable with dart code. You need to call flutter command in order to de-obfuscate your error. You may try get stacktrace with Catcher and then follow this section: https://flutter.dev/docs/deployment/obfuscate#reading-an-obfuscated-stack-trace
