### ISSUE TITLE
[BUG] Error Flutter 2

### ISSUE THREAD

**Issue by ufukhawk** [jhomlala/catcher#147]
Because catcher >=0.3.21 depends on mailer ^3.2.1 which depends on mime >0.9.0 <1.0.0, catcher >=0.3.21 requires mime >0.9.0 <1.0.0.
And because share >=2.0.0 depends on mime ^1.0.0, catcher >=0.3.21 is incompatible with share >=2.0.0.
So, because xxxx depends on both share ^2.0.0 and catcher ^0.4.2, version solving failed.
pub get failed (1; So, because xxxx depends on both share ^2.0.0 and catcher ^0.4.2, version solving failed.)

**Comment by jhomlala** [comment]
You need to use latest Catcher version. Right now Catcher is in process of null safety implementation, so you need to use this temp fix: https://github.com/jhomlala/catcher/issues/139#issuecomment-792274300
