### ISSUE TITLE
[BUG] Catcher 0.4.2 incompatible with share 2.0.0 and mailer 4.0.0

### ISSUE THREAD

**Issue by jhandaya** [jhomlala/catcher#148]
**Describe the bug**

Incompatible with Share library because of dependency on mime (not the latest)

**To Reproduce**
1. Pubspec.yaml
2.  add
     catcher: ^0.4.2
     share: ^2.0.0

3. go terminal and -> flutter pub get

**Expected behavior**
Update your package dependency to use the latest package from mailer (4.0.0) as the date i send this

**Screenshots**

Because catcher >=0.3.21 depends on mailer ^3.2.1 which depends on mime >0.9.0 <1.0.0, catcher >=0.3.21 requires mime >0.9.0 <1.0.0.

And because share >=2.0.0 depends on mime ^1.0.0, catcher >=0.3.21 is incompatible with share >=2.0.0.

**Flutter doctor**
Please add flutter doctor output here.

**Catcher version**
- Version: 0.4.2

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A

**Additional context**

**Comment by ThexXTURBOXx** [comment]
You have to wait until the null-safety update of `catcher` is released :)

**Comment by jhomlala** [comment]
Please upgrade to Catcher 0.5.0.
