### ISSUE TITLE
Reporting device name is not anonymous

### ISSUE THREAD

**Issue by smartyboy** [jhomlala/catcher#158]
Catcher reports name and utsnameNodename which in my mind is identifiable information.
E.g. on iOS I found the name of my phone twice:
```
model: iPhone
isPhysicalDevice: true
name: **John Smith's iPhone**
identifierForVendor: 1A2B3C4D-0000-01AB-23CD-033FFFF4F9A0
localizedModel: iPhone
systemName: iOS
utsnameVersion: Darwin Kernel Version 19.5.0: Tue May 26 20:56:31 PDT 2020; root:xnu-6153.122.2~1/RELEASE_ARM64_T8015
utsnameRelease: 19.5.0
utsnameMachine: iPhone10,5
utsnameNodename: **John-Smiths-iPhone**
utsnameSysname: Darwin
```

Many people have their first and last name as their phone name and if you have a name combination less common than John Smith it violates the anonymous promise of every report. identifierForVendor should be enough to identify if report is from the same user/phone.

Can these fields be omitted or made optional?

**Comment by jhomlala** [comment]
@smartyboy Yes, you're right. I will add some opt-in feature for these parameters in next releases.

**Comment by jhomlala** [comment]
Added in 0.6.4 release.
