### ISSUE TITLE
Already have a navigatorKey in my project.

### ISSUE THREAD

**Issue by davidhsu1115** [jhomlala/catcher#16]
As title, my project already has a navigatorKey to controller other things.
How can I add Catcher.navigatorKey to my project?

Thanks.

**Comment by anasiqbal** [comment]
Hi,

What's the solution to this?

**Comment by anasiqbal** [comment]
> As title, my project already has a navigatorKey to controller other things.
> How can I add Catcher.navigatorKey to my project?
> 
> Thanks.

Did you found a solution? can you please post it here?

Thanks

**Comment by deadsoul44** [comment]
@jhomlala  What is the solution? I already have navigator key due to Sailor (a navigator package). Thank you.
