### ISSUE TITLE
[BUG] Change package_info to package_info_plus

### ISSUE THREAD

**Issue by narumishi** [jhomlala/catcher#161]
As `package_info` only support Android/iOS/macOS currently. The following code will raise error in windows (and maybe linux)
https://github.com/jhomlala/catcher/blob/0d03422643a45b440eebfc0408204d5f86469ad5/lib/core/catcher.dart#L388-L401

`package_info_plus` support all platforms including Web.
```dart
  void _loadApplicationInfo() {
    _applicationParameters["environment"] =
        describeEnum(ApplicationProfileManager.getApplicationProfile());

  /// package_info_plus support all platforms
    PackageInfo.fromPlatform().then((packageInfo) {
      _applicationParameters["version"] = packageInfo.version;
      _applicationParameters["appName"] = packageInfo.appName;
      _applicationParameters["buildNumber"] = packageInfo.buildNumber;
      _applicationParameters["packageName"] = packageInfo.packageName;
    });
  }
```

If you don't want to use `package_info_plus`, please change `!ApplicationProfileManager.isWeb()` to 
`ApplicationProfileManager.isAndroid || ApplicationProfileManager.isIos || ApplicationProfileManager.isMacOS`

**Comment by narumishi** [comment]
By the way, it would helpful to make `_deviceParameters` and `_applicationParameters` **public**.

**Comment by jhomlala** [comment]
Added in 0.6.5. You can use excluded parameters to remove parameters from deviceParameters. You can also add custom parameters to report.

**Comment by narumishi** [comment]
Actually, I want to reuse and access some parameters outside Catcher(e.g. by clicking 'send feedback' to manually send email only background), my class methods cannot access these params. Or I need to rewrite all platform and app info methods.

What about something like this, it won't change the original map.
```dart
Map<String, dynamic> get deviceParameters => Map.from(_deviceParameters);
Map<String, dynamic> get applicationParameters => Map.from(_applicationParameters);
```
