### ISSUE TITLE
[FEATURE] Replace fluttertoast with bot_toast or flutter_easyloading in ToastHandler to support desktop

### ISSUE THREAD

**Issue by narumishi** [jhomlala/catcher#162]
`fluttertoast` only support Android, iOS and Web. 
`bot_toast` and `flutter_easyloading` support all platforms.

**Comment by jhomlala** [comment]
bot_toast and flutter_easyloading didn't meet my requirments. Anyway I've resolved it with fluttertoast. Check version 0.6.4.

**Comment by narumishi** [comment]
Forgot to change the supported platforms of ToastHandler
https://github.com/jhomlala/catcher/blob/1231ae06eff5d0a7278688fce781141a8b1838c3/lib/handlers/toast_handler.dart#L102-L106
