### ISSUE TITLE
[FEATURE] Allow handlers run even when rejected

### ISSUE THREAD

**Issue by narumishi** [jhomlala/catcher#164]
**Is your feature request related to a problem? Please describe.**
In dialog or page report mode, Cather will do nothing if user rejected. 

However, like `ConsoleHandler`, `ToastHandler` and `FileHandler` should be run in most cases even user rejected, since they are handled in local.

For email, sentry and other handlers which will send http request should be handled according to user's action.

**Describe the solution you'd like**
Pass a parameter to all handlers like `alwaysHandle`. Handle it inside both `onReject` and `onAccept`. 

**Additional context**
When press backButton in `PageReportMode` or dissmiss dialog in `DialogReportMode`, Catcher will do nothing.
They should do the same as user reject.

**Comment by jhomlala** [comment]
@narumishi If you want to auto handle reports, why don't just use silent report mode?

**Comment by narumishi** [comment]
As I said, sending email and other network-related handlers should require user's confirm which may collect and send user's information to developer.

But logging locally should always be done since it never send any data to developer. 

With current solution, for example, email handler and logging file handler, and I attach log file into email. If user rejects 10 times, and accepts 1 time, log file only contains one error. But if logging file handler is always done even rejected, I can access 11 errors in log file at last.

**Comment by jhomlala** [comment]
Added possibility to handle rejected reports in Catcher 0.6.6.
