### ISSUE TITLE
[Question] How to make debug version default?

### ISSUE THREAD

**Issue by Mayb3Nots** [jhomlala/catcher#165]
I want the default debugger options when in debug mode. Putting `null `in `debugConfig `doesn't make it the default instead prints our the catcher version of debug. I just want to use catcher for production mode.

**Comment by jhomlala** [comment]
I don't understand your question. Can you elaborate it?

**Comment by Mayb3Nots** [comment]
Basicly i dont want catcher to do anything as if the plugin is not there for debug version. Cause right now when exception is cuaght its the catcher debugger type not default

**Comment by jhomlala** [comment]
So If you don't want to do anything in debug version simply don't setup Catcher for debug. Simply check in main if app is running in debug mode and don't init Catcher.

**Comment by Mayb3Nots** [comment]
> So If you don't want to do anything in debug version simply don't setup Catcher for debug. Simply check in main if app is running in debug mode and don't init Catcher.

How do you know if release is in debug or production?
