### ISSUE TITLE
[FEATURE]add `copyWith` method for `LocalizationOptions`

### ISSUE THREAD

**Issue by narumishi** [jhomlala/catcher#171]
`copyWith` is used everywhere in flutter. It helps a lot if we just want to modify only some options.

BTW, localized values for Chinese inside `buildDefaultChineseOptions`:
- `dialogReportModeTitle` and `pageReportModeTitle`: original value is `"紧急"`(means emergency), maybe `"错误"`(means error) is better in Chinese.
- `toastHandlerDescription`: change `"發生了錯誤:"`  to `"发生了错误:"`. The former is Traditional Chinese not Simplified Chinese.

**Comment by jhomlala** [comment]
Added/fixed in Catcher 0.6.6.
