### ISSUE TITLE
[FEATURE] Add report filter before handling it

### ISSUE THREAD

**Issue by narumishi** [jhomlala/catcher#172]
**Describe the solution you'd like**
Some errors like known but not fixed bugs of flutter framework, network errors, these should not always be reported to user.

Add a handler to decide whether to submit this report or not. 
For example, pass a param to Catcher: `bool filter(Report report)?`,
and call inside `_reportError`:
`if(filter!=null&&!filter(report)) return;` to ignore this error.

**Comment by jhomlala** [comment]
@narumishi You can use explicit exception map to filter these exceptions to some custom dump report handler (which won't do anything with them).

**Comment by narumishi** [comment]
It could be a solution in some situations. Explicit exception map use `error.toString().contains(keyword)` to get custom handler/report mode. But no stackTrace check. 

For example, I'm facing such a bug not fixed by flutter yet: `RangeError: Value not in range X`, where the stackTrace will always be
```
#0      _StringBase.substring (dart:core-patch/string_patch.dart:399:7)
#1      TextRange.textBefore (dart:ui/text.dart:2750:17)
#2      RenderEditable.delete (package:flutter/src/rendering/editable.dart:1119:37)
#3      _DeleteTextAction.invoke (package:flutter/src/widgets/default_text_editing_actions.dart:88:45)
#4      ActionDispatcher.invokeAction (package:flutter/src/widgets/actions.dart:517:21)
```  

If error is raised from above code, it should pass to a silent handler, otherwise not. But if I use explicit exception map, it will pass all range error to it.

If change `explicitExceptionHandlersMap` from `Map<String, ReportHandler>` to a `ReportHandler Function(Report report)`, it could be great.

My current solution is create a custom report mode and filter report inside `requestAction`.

**Comment by jhomlala** [comment]
Added filterFunction in CatcherOptions in Catcher 0.6.6.
