### ISSUE TITLE
[BUG] same error results in multiple calls in release/profile build

### ISSUE THREAD

**Issue by Gafielt** [jhomlala/catcher#179]
**Describe the bug**
Currently it is possible for an Layout error to result in multiple calls (=dialog pop ups), which ask the user to send the report. This should not be the case since their is only one reason this error gets thrown. In my example it's an invalid constraint (maxWidth<minWidth). Such error are in my opinion common and should not result in this behavior. This is only the case if the app gets build in release or profile mode, in debug everything is as expected.

**To Reproduce**
execute the given code snippet in release or profile mode and press the text "press". This should open a dialog with an invalid constrained box.

```
import 'package:catcher/catcher.dart';
import 'package:flutter/material.dart';

void main() {
  Catcher(
    rootWidget: SimpelApp(),
    navigatorKey: GlobalKey<NavigatorState>(),
    profileConfig: CatcherOptions(
      DialogReportMode(),
      [
        ConsoleHandler(),
      ],
    ),
    debugConfig: CatcherOptions(
      DialogReportMode(),
      [
        ConsoleHandler(),
      ],
    ),
  );
}

class SimpelApp extends StatefulWidget {
  @override
  _SimpelAppState createState() => _SimpelAppState();
}

class _SimpelAppState extends State<SimpelApp> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Catcher Test',
      navigatorKey: Catcher.navigatorKey,
      home: home(),
    );
  }
}

class home extends StatelessWidget {
  const home({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(title: Text('Catcher Test')),
        body: Center(
          child: InkWell(
            child: Text("press"),
            onTap: () => showDialog(
                context: context,
                builder: (context) => Dialog(
                      child: LayoutBuilder(builder: (context, constraints) {
                        return Column(
                          children: [
                            Text("headline"),
                            ConstrainedBox(
                              constraints: constraints.copyWith(maxWidth: 50,minWidth: 200),
                              child: InkWell(
                                child: Text("close"),
                                onTap: () => Navigator.of(context).pop(),
                              ),
                            )
                          ],
                        );
                      }),
                    )),
          ),
        ));
  }
}
```

**Expected behavior**
As it is in debug version.

**Screenshots**
Wanted behavior:
![Screenshot_20210531-202244_Kheladi Demo](https://user-images.githubusercontent.com/57099610/120229748-145fea80-c24e-11eb-8842-554c2cc94c25.jpg)
(red space should be white/grey due to release/profile anyway)

Actual behavior:
![Screenshot_20210531-202041_Kheladi Demo](https://user-images.githubusercontent.com/57099610/120229637-d367d600-c24d-11eb-84be-531bf4131934.jpg)
(black screen due to stacking of multiple dialogs)

**Flutter doctor**
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.2.1, on Microsoft Windows [Version 10.0.19042.985], locale de-DE)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.56.2)
[√] Connected device (2 available)

! Doctor found issues in 1 category.
```

**Catcher version**
- Version: 

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S10
 - OS: Android 11

**Additional context**

**Comment by jhomlala** [comment]
@Gafielt This will be fixed in next release.

**Comment by jhomlala** [comment]
Please upgrade to 0.6.7 and use `reportOccurrenceTimeout` to prevent situation like yours.
