### ISSUE TITLE
[Bug report] Error in debug mode

### ISSUE THREAD

**Issue by jasonlaw** [jhomlala/catcher#18]
Hi @jhomlala ,

I get this error during the debug mode.

![image](https://user-images.githubusercontent.com/107820/57115477-c849cf80-6d81-11e9-9be8-09eca6c75dfb.png)

![image](https://user-images.githubusercontent.com/107820/57115490-d13aa100-6d81-11e9-99f8-97f6b33159d7.png)

Here is my code:
![image](https://user-images.githubusercontent.com/107820/57115499-d992dc00-6d81-11e9-97e9-e05006cc18c5.png)

Thanks in advance.

**Comment by jhomlala** [comment]
Which Catcher version are you using? Can you provide code where error happened?
