### ISSUE TITLE
[BUG] Cmake error when running flutter in desktop mode on linux.

### ISSUE THREAD

**Issue by jordan-lumley** [jhomlala/catcher#180]
**Describe the bug**
Hi there, 

First time user of this library but after adding catcher as a dependency for my project, I am getting an error about the source directory not containing the CMakeLists.txt file. 

**To Reproduce**
1. Added catcher as a dep.
2. Copied example into my main.dart project
3. Tried to run the project

**Expected behavior**
The project to run.

**Screenshots**
![image](https://user-images.githubusercontent.com/57803850/121405712-5f9f8a80-c92b-11eb-82e6-a7a36a0c4ccb.png)

**Flutter doctor**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.1, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 4.1)
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.56.2)
[✓] Connected device (2 available)

• No issues found!

**Catcher version**
- Version: 0.6.6

**Smartphone (please complete the following information):**
 - Device: Desktop
 - OS: Linux, Zorin (debian)

**Additional context**

**Comment by jhomlala** [comment]
Added missing CMakeLists.txt for linux in 0.6.7.
