### ISSUE TITLE
Add custom logging option for internal logging

### ISSUE THREAD

**Issue by 0ttik** [jhomlala/catcher#184]
It would be good to be able to provide custom logger implementation to catcher to keep logs consistent throughout the app. 

It doesn't seem like a lot to do, so I can try to provide MR if you think it's useful.

I think of a simple interface like: 
```
abstract class CatcherInternalLogger {
    void log(String message);
}
```

**Comment by jhomlala** [comment]
Added support for custom logger in 0.6.7. Here's an example: https://github.com/jhomlala/catcher/blob/master/example/lib/custom_logger_example.dart
