### ISSUE TITLE
[FEATURE] Changing behavior based on the type of error

### ISSUE THREAD

**Issue by smbody** [jhomlala/catcher#186]
If the user does not use the application for a long time, his token may become outdated. And if an error occurs when you try to update it, we must go to the authentication page instead of the error page.

Maybe we can do this with new custom report mode?

**Comment by jhomlala** [comment]
You should create custom report handler which will handle your custom scenario.

```dart
import 'package:catcher/catcher.dart';
import 'package:catcher/model/platform_type.dart';
import 'package:flutter/src/widgets/framework.dart';

class CustomReportHandler extends ReportHandler {
  @override
  List<PlatformType> getSupportedPlatforms() {
    ...
  }

  @override
  Future<bool> handle(Report error, BuildContext context) {
    ...
  }
}
```

If you need to use specific handler for error then use Explicit exception report handler map: https://github.com/jhomlala/catcher#explicit-exception-report-handler-map
