### ISSUE TITLE
XCode build error: Catcher v0.6.7

### ISSUE THREAD

**Issue by shobhit14gupta** [jhomlala/catcher#192]
I upgraded the catcher to v0.6.7 from v0.6.3. During build process, I got the Xcode build error stating  

.../../catcher-0.6.7/lib/model/report_handler.dart
"Error: Expected a declaration, but got  4"
 
This was the line : 4import 'package:catcher/model/platform_type.dart';

Catcher Version**
- Version: 0.6.7

**Comment by jhomlala** [comment]
@shobhit14gupta I've tested 0.6.7 release on iOS there was no problem reported by you. I also didn't find any line with 
`4import 'package:catcher/model/platform_type.dart';`.
