### ISSUE TITLE
[BUG] Unhandled Exception: Unsupported operation: Functionality only available on Android (MethodChannelPathProvider.getExternalStoragePath)

### ISSUE THREAD

**Issue by limsocheat** [jhomlala/catcher#193]
**Describe the bug**
Try to add screenshot path. Got the UnsupportedError as below: 

```[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: Unsupported operation: Functionality only available on Android
#0      MethodChannelPathProvider.getExternalStoragePath (package:path_provider_platform_interface/src/method_channel_path_provider.dart:55:7)
#1      getExternalStorageDirectory (package:path_provider/path_provider.dart:155:40)
#2      CatcherConfig._getPath (package:app/configs/catcher_config.dart:28:27)
#3      CatcherConfig.debugOptions (package:app/configs/catcher_config.dart:11:30)
#4      mainCommon (package:app/main.dart:20:60)
<asynchronous suspension>
```

**To Reproduce**
Follow the example here: https://github.com/jhomlala/catcher/blob/master/example/lib/screenshot_example.dart

```
Directory? externalDir;
  if (Platform.isAndroid || Platform.isIOS) {
    externalDir = await getExternalStorageDirectory();
  }
  if (Platform.isMacOS) {
    externalDir = await getApplicationDocumentsDirectory();
  }
  String path = "";
  if (externalDir != null) {
    path = externalDir.path.toString();
  }
```

**Expected behavior**
Expected not to throw any UnsupportedError

**Screenshots**
<img width="1066" alt="Screen Shot 2021-08-17 at 11 19 19 AM" src="https://user-images.githubusercontent.com/6656644/129663008-1ee467b2-217e-4655-aa1a-ca616681987e.png">

**Flutter doctor**
`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.2 20G95 darwin-x64, locale en-AU)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[!] Android Studio (version 2020.3)
    ✗ Unable to find bundled Java version.
[✓] VS Code (version 1.59.0)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.
`

**Catcher version**
- Version: 0.6.8

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone 12 Simulator]
 - OS: [e.g. iOS14.5]

**Additional context**
N/A

**Comment by jhomlala** [comment]
Fixed in 0.6.9.
