### ISSUE TITLE
[BUG] It does not catch SYNCHRONOUS ERRORS

### ISSUE THREAD

**Issue by topperspal** [jhomlala/catcher#195]
Just try to remove `async` keyword from the method below ( given in first example of the readme ) and it will not catch the error

### BEFORE
```
generateError() async {
    throw "Test exception";
 }
```
### AFTER
```
generateError() {
    throw "Test exception";
 }
```

**Comment by jhomlala** [comment]
Please use search function next time: https://github.com/jhomlala/catcher/issues/75#issuecomment-615720375

@mikeesouth If problem still occurs in release mode, please create ticket with reproducible example.
