### ISSUE TITLE
Dismiss the the dialog for, form after accept

### ISSUE THREAD

**Issue by jasonlaw** [jhomlala/catcher#20]
Hi @jhomlala ,

For now, after accepting from the dialog form, the dialog form will not be dismissed until we click on the cancel button. Can we make it to dismiss once the accept button is clicked?
Thanks in advance.

**Comment by jhomlala** [comment]
It should be auto dismissed after "Accept" click. Which catcher version are you using? Can you provide example code?

**Comment by jhomlala** [comment]
If you need additional advice, please open new ticket.
