### ISSUE TITLE
Internet connection error

### ISSUE THREAD

**Issue by jasonlaw** [jhomlala/catcher#22]
It is pretty weird to catch and report the internet connection error, especially when user are in the bad internet reception. For this kind of error, can we just pop up a alert box instead of report page? Is there a way to configure that?

Thanks in advance.

**Comment by jhomlala** [comment]
Hi @jasonlaw , you can use DialogReportMode:
https://github.com/jhomlala/catcher#dialog-report-mode

**Comment by jhomlala** [comment]
If you need additional advice, open new ticket.
