### ISSUE TITLE
It is strongly recommended that 

### ISSUE THREAD

**Issue by ZhangZhiH** [jhomlala/catcher#226]
Unable to stores
Obtained android ID before accepting the agreement
Can this add option to turn off get Android ID

**Comment by calcitem** [comment]
I don't understand what you are saying.

**Comment by ZhangZhiH** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
