### ISSUE TITLE
[BUG] After installing catcher package the scroll becomes very fast

### ISSUE THREAD

**Issue by synapticweb** [jhomlala/catcher#228]
**Describe the bug**
I have an app that I test on a M1 MacBook machine using the Ios simulator. After installing the catcher flutter package, the scroll becomes abnormally fast. I believe the issue is identical with the problem described here: 

[https://stackoverflow.com/questions/68223330/ios-simulator-inertia-while-scrolling](url)

because the proposed workaround (running the simulator with Rosetta) reverts the scroll speed back to normal.

**To Reproduce**
1. Create a fresh flutter app.
2. Put a ListView with enough items to generate scroll in the main view.
3. Run app on Ios simulator, M1 chip. Try to scroll, the speed is normal.
4. Install catcher package in pubspec.yaml, run flutter pub get.
5. Stop the app.
6. Build the app again. Run it on Ios simulator, M1 chip.
7. Try to scroll: the scrolling is extremely fast.
8. Run the simulator with rosetta: the scroll speed is normal.

**Expected behavior**
The scroll speed should be normal with catcher installed, even without rosetta.

**Flutter doctor**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.4, on macOS 12.2.1 21D62 darwin-arm, locale en-RO)
[!] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google
    Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 2021.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

**Catcher version**
- Version: 0.6.9

**Smartphone (please complete the following information):**
 - Device: Ios simulator, every phone model
 - OS: Ios 15.5

**Comment by jhomlala** [comment]
I assume this was because of the M1 issues, but if the problem is still happening, please let me know.
