### ISSUE TITLE
[BUG] catcher >=0.6.9 depends on device_info_plus ^3.1.1 and our app depends on device_info_plus ^4.0.1, catcher >=0.6.9 is forbidden

### ISSUE THREAD

**Issue by Husnain-Asharf** [jhomlala/catcher#229]
**Describe the bug**
catcher >=0.6.9 depends on device_info_plus ^3.1.1 and our app depends on device_info_plus ^4.0.1, catcher >=0.6.9 is forbidden

This package device_info_plus dependency need to update.

**Comment by ThexXTURBOXx** [comment]
See #218
