### ISSUE TITLE
Explicit exception for internet connectivity issue

### ISSUE THREAD

**Issue by jasonlaw** [jhomlala/catcher#23]
Hi @jhomlala ,

I would like to prevent to dialog box with "Accept/Cancel" button when there is internet connection issue. I configure the explicitExceptionHandlersMap as shown below. I tested with my phone by shutting down the wifi and mobile data. It hit an error and pop up the Dialog box with Accept/Cancel button. If I click on the Accept button, the toast will be displayed with my custom message. I expect when hitting error it show straight away show the toast without the dialog box. Did I miss anything?

![image](https://user-images.githubusercontent.com/107820/58771296-e3f4ff80-85e5-11e9-89cd-ec250f7e1d15.png)

**Comment by jhomlala** [comment]
I'll work on this feature. Thanks for idea!

**Comment by jhomlala** [comment]
https://github.com/jhomlala/catcher#explicit-exception-report-mode-map

Please use Catcher 0.1.8 for this feature.
