### ISSUE TITLE
[BUG] Catcher uses fluttertoast which has a conflict with cloud_firestore

### ISSUE THREAD

**Issue by buzzware** [jhomlala/catcher#233]
I have removed catcher from my project because of this issue :
See https://github.com/firebase/flutterfire/issues/9641

**Catcher version**
- Version: 0.6.9

**Smartphone (please complete the following information):**
 - Device: iPhone Simulator
 - OS: iOS 13.5

Error :

```
Can't merge user_target_xcconfig for pod targets: ["FirebaseFirestore", "AutodetectLeveldb", "Base", "WithLeveldb", "fluttertoast"]. Singular build setting EXCLUDED_ARCHS[sdk=iphonesimulator*] has different values.
```

**Comment by jhomlala** [comment]
Please update to version `0.8.0`.
