### ISSUE TITLE
[BUG] Missing CMakeLists.txt on windows

### ISSUE THREAD

**Issue by toheiss-btc** [jhomlala/catcher#236]
**Describe the bug**
Hi all,
after adding Catcher to my project, I get an error message about the source directory not containing the CMakeLists.txt file.

**To Reproduce**
1. Added catcher as a dep.
2. Tried to run the project

**Expected behavior**
The project to run.

**Screenshots**
![image](https://user-images.githubusercontent.com/117382282/206149290-43668b85-8642-4cb9-8d42-aa0184bfb142.png)

**Flutter doctor**
• No issues found!

**Catcher version**
- Version: ^0.7.0

**Smartphone (please complete the following information):**
 - Device: Windows (windows-x64)
 - OS: Windows 10

**Comment by mrclauss** [comment]
Same here. The CMakeLists.txt file is present in the github repository, but when the package is fetched by "pub get" the local .pub-cache folder does not contain it...

**Comment by bmcclure** [comment]
Agreed. I initially realized I was using catcher 0.5.0, which did have a cmakelists.txt file, but after I updated to 0.7.0, the file disappeared.

**Comment by narumi147** [comment]
The platform codes are added just to display all platform support on pub.dev, except that, the platform codes are useless.
I have already told the problem and solution several times, but I cannot understand why the author keeps ignoring my advice.
I create a folk to remove all platform codes.
- https://github.com/jhomlala/catcher/issues/200#issuecomment-1335186712

**Comment by calcitem** [comment]
A similar problem will also occur with a fresh compilation under Linux:

```
[ +139 ms] CMake Error at flutter/generated_plugins.cmake:18 (add_subdirectory):
[        ]   The source directory
[        ]     /root/parts/mill/build/src/ui/flutter_app/linux/flutter/ephemeral/.plugin_symlinks/catcher/linux
[        ]   does not contain a CMakeLists.txt file.
[        ] Call Stack (most recent call first):
[        ]   CMakeLists.txt:144 (include)
[  +10 ms] -- Configuring incomplete, errors occurred!
```

**Comment by kevinxxq** [comment]
> 

Hi,
Thank you for your fork, I have a question, will your fork still generate a catcher_pulgin.dll on windows?

I tried today and found no such dll file and the App crashed but the issue is still not confirmed since I updated the sdk to 3.10.0 too.

Thank you.

**Comment by kevinxxq** [comment]
> 

Hi,
Thank you for your fork, I have a question, will your fork still generate a catcher_pulgin.dll on windows?

I tried today and found no such dll file and the App crashed but the issue is still not confirmed since I updated the sdk to 3.10.0 too.

Thank you.

**Comment by kevinxxq** [comment]
> The platform codes are added just to display all platform support on pub.dev, except that, the platform codes are useless. I have already told the problem and solution several times, but I cannot understand why the author keeps ignoring my advice. I create a folk to remove all platform codes.
> 
> * [What's the purpose of `getPlatformVersion`? #200 (comment)](https://github.com/jhomlala/catcher/issues/200#issuecomment-1335186712)
> 
> the fork with some fixes:
> 
> * https://github.com/narumi147/catcher

Hi,
Thank you for your fork, I have a question, will your fork still generate a catcher_pulgin.dll on windows?

I tried today and found no such dll file and the App crashed but the issue is still not confirmed since I updated the sdk to 3.10.0 too.

Thank you.

**Comment by kevinxxq** [comment]
Hi @narumi147 
Thank you for reply and quick action, just as you said, I rolled back to flutter sdk 3.7.12 since too many dependencies need be taken care of. It works well with original 0.6.9.

I will try your fork when flutter sdk 3.10 is "stable" enough.
Thank you again.

**Comment by jonas-martinez** [comment]
@narumi147 You fork has fixed the issue :smile:. Thank you for your work!

It would still be better if these changes were done on @jhomlala's project, why can't it be done?

**Comment by mrclauss** [comment]
Because it seems he doesn't maintain/work on that thing any more. Please consider raising a PR to this fork which already contains fixes for lots of other issues:
https://github.com/ThexXTURBOXx/catcher

**Comment by jhomlala** [comment]
Please update to version `0.8.0`.
