### ISSUE TITLE
[BUG] Crash on iOS 14.X simulator when using [catcher] and [in_app_purchase] together.

### ISSUE THREAD

**Issue by sneglia9191** [jhomlala/catcher#237]
[sneglia9191](https://github.com/sneglia9191) commented [2 days ago](https://github.com/flutter/flutter/issues/118500#issue-1533237466)
Via issue https://github.com/flutter/flutter/issues/117842, I have been working with the in_app_purchase team as it appear there is a conflict between in_app_purchase and the catcher packages. What happens is I am getting a hard crash when purchasing a non-consumable on IOS simulators with 14.X. It does not crash on a simulator with 16.2. It also works in the sandbox environment on a physical device running 14.8.1. Working with the in_app_purchase team, there is a conflict with the catcher plug-in.

All details and information are in issue https://github.com/flutter/flutter/issues/117842. The in_app_purchase team has asked that I contact you as they can not step deeper into your code to debug.

**Comment by sneglia9191** [comment]
Hello - any status updates on this?   I have confirmed there is a conflict with the [Catcher] plugin and the [in_app_purchase] plug-in.  This is still an issue.

**Comment by ThexXTURBOXx** [comment]
See #234

**Comment by jhomlala** [comment]
Looks like problem has been resolved on in_app_purchases. I expect this problem is no longer happening.
