### ISSUE TITLE
Not work for red page?

### ISSUE THREAD

**Issue by wxlcat** [jhomlala/catcher#24]
# How to replace default red page when exceptions occurred? 
![image](https://user-images.githubusercontent.com/3508825/59254995-d71a8080-8c63-11e9-8dcf-d69c3b6cc658.png)

**Comment by jhomlala** [comment]
Hi, I'll add feature to replace red page in Catcher in next versions. Thanks for reporting!

**Comment by jhomlala** [comment]
Check version 0.1.7, which has error widget support.

**Comment by jhomlala** [comment]
https://github.com/jhomlala/catcher#error-widget
