### ISSUE TITLE
LateError (LateInitializationError: Field 'screenshotManager' has not been initialized.)

### ISSUE THREAD

**Issue by dingkangtan** [jhomlala/catcher#248]
**Describe the bug**
After upgraded Flutter version to 3.10.4 with enabled debugger "All exceptions" will appear this exception. 

**Flutter doctor**
Flutter (Channel stable, 3.10.4, on macOS 13.2.1 22D68 darwin-x64, locale en-SG)
    • Flutter version 3.10.4 on channel stable at /Users/x/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 682aa387cf (6 days ago), 2023-06-05 18:04:56 -0500
    • Engine revision 2a3401c9bb
    • Dart version 3.0.3
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/x/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.66.0

[✓] Connected device (4 available)
    • Pixel 2 XL (mobile)           • 712KPUU1158086            • android-arm64  • Android 11 (API 30)
    • macOS (desktop)               • macos                     • darwin-x64     • macOS 13.2.1 22D68 darwin-x64
    • Chrome (web)                  • chrome                    • web-javascript • Google Chrome 114.0.5735.106

[✓] Network resources
    • All expected network resources are available.

**Catcher version**
- Version: 0.7.0

**Smartphone (please complete the following information):**
 - Device: Pixel 2 XL
 - OS: Android 11 (API 30)

**Additional context**
The error only appear in Android.

**Comment by ThexXTURBOXx** [comment]
See #234

**Comment by jhomlala** [comment]
Please update to version `0.8.0`.

**Comment by sandeep2569** [comment]
@jhomlala this issue is not fixed still getting the same error ==> **LateInitializationError: Field 'screenshotManager' has not been initialized.**

**Comment by ThexXTURBOXx** [comment]
@sandeep2569 This issue is fixed in `catcher_2`
