### ISSUE TITLE
Dependency on old device_info_plus

### ISSUE THREAD

**Issue by Mmisiek** [jhomlala/catcher#249]
Because syncfusion_flutter_pdfviewer >=22.1.34 depends on device_info_plus ^9.0.2 and catcher >=0.7.0 depends on device_info_plus ^7.0.0, syncfusion_flutter_pdfviewer >=22.1.34 is incompatible with catcher >=0.7.0.
So, because pest_scope depends on both catcher ^0.7.0 and syncfusion_flutter_pdfviewer ^22.1.34, version solving failed.

**Comment by calcitem** [comment]
https://github.com/jhomlala/catcher/pull/234

**Comment by jhomlala** [comment]
Please update to version `0.8.0`.
