### ISSUE TITLE
flutter_local_notifications version conflict

### ISSUE THREAD

**Issue by handsomeceleste** [jhomlala/catcher#25]
Because catcher >=0.0.11 depends on flutter_local_notifications ^0.5.1 and my app depends on flutter_local_notifications ^0.7.1+3, catcher >=0.0.11 is forbidden.

So, because my app depends on catcher ^0.1.5, version solving failed.

Do you have a plan to upgrade to latest flutter_local_notifications version?

**Comment by jhomlala** [comment]
Hi, I've released 0.1.6 version with updated depdencies. It should fix your problem.
