### ISSUE TITLE
[FEATURE] Isn't it necessary to support iOS privacy manifesta?

### ISSUE THREAD

**Issue by ShuheiSuzuki-07** [jhomlala/catcher#267]
Nice to meet you, I have always been a fan of this plugin. Thank you very much.

Now, Apple is asking for Privacy Manifest support. Various plugins are affected by this.
This plugin (Catcher) uses FlutterToast internally, and FlutterToast is subject to Privacy Manifest compliance. Therefore, after the FlutterToast support is completed, we believe it is necessary to incorporate it in the Catcher side as well.

Thank you in advance for your support.

Please let us know if there is any error in our understanding.

FlutterToast Privacy Manifest Issue : https://github.com/ponnamkarthik/FlutterToast/issues/481

**Comment by SputNikPlop** [comment]
@ShuheiSuzuki-07 I have patched it upstream for fluttertoast, the same would basically apply to this package.

**Comment by ShuheiSuzuki-07** [comment]
I opened an issue on this.
https://github.com/jhomlala/catcher/issues/269

**Comment by jhomlala** [comment]
Fixed in https://pub.dev/packages/catcher/versions/1.0.0-dev1
