### ISSUE TITLE
[FEATURE] Urgent: Update dependent packages

### ISSUE THREAD

**Issue by ShuheiSuzuki-07** [jhomlala/catcher#269]
**Is your feature request related to a problem? Please describe.**
The `device_info_plus` and `package_info_plus` on which this plugin depends provide the latest versions. Updates to these dependent packages include compliance with Apple's privacy policy.
This means that if you do not comply with this, your app will soon not be able to pass Apple's review process.
This will affect many users and needs to be addressed immediately.

**Describe the solution you'd like**
Update pubspec.yaml

**Describe alternatives you've considered**
Nothing.

**Additional context**
This is urgent. We hope to have a response as soon as possible.

**Comment by ShuheiSuzuki-07** [comment]
I created PR
https://github.com/jhomlala/catcher/pull/270

**Comment by ShuheiSuzuki-07** [comment]
@jhomlala 
Is it possible to respond about this?
We are aware that maintaining the OSS requires a great deal of effort.
However, we would be happy to hear your policy at least.

This issue has a major impact on many products that are indebted to this plugin.
(This is because this plugin is about architecture)

I would like to cooperate with you as much as possible.

**Comment by calcitem** [comment]
See https://github.com/ThexXTURBOXx/catcher_2/releases/tag/1.2.4

**Comment by ShuheiSuzuki-07** [comment]
@calcitem 
Thank you for your information.
We will consider including package migration.

**Comment by nildakuzu** [comment]
Hello,
Dependent packages (**device_info_plus**, **package_info_plus**, **fluttertoast**) have been updated for Apple's privacy policy. Can you update these dependent packages in Catcher?

Thank you for your continuous commits.

**Comment by jhomlala** [comment]
Fixed in latest release: https://pub.dev/packages/catcher/versions/1.0.0-dev1
