### ISSUE TITLE
version of dio.

### ISSUE THREAD

**Issue by yohom** [jhomlala/catcher#3]
Can the version of `dio` be promoted to 2.0.0? Or remove the dependence on dio, thank you very much.

**Comment by jhomlala** [comment]
Updated Dio to 2.0.0. I can see that 2.0.0 may have issues, so if something unexpected happens with HttpHandler please open new issue.

**Comment by jhomlala** [comment]
Please install version ^0.0.9 to use Dio 2.0.0
