### ISSUE TITLE
ConsoleHandler not triggered.

### ISSUE THREAD

**Issue by MichalMisiaszek** [jhomlala/catcher#32]
Hi,
I have debug config like: 
```CatcherOptions debugOptions = CatcherOptions(PageReportMode(), [ ConsoleHandler(), EmailManualHandler(["techsupport@blabla.com"])]);```

When exception happens the page report opens but there is nothing in console. 

Dzieki

**Comment by jhomlala** [comment]
You need to click accept in new Page to log error in your console.

**Comment by jhomlala** [comment]
If your problem still occurs, please open new ticket with your example code and flutter doctor command output.

**Comment by MichalMisiaszek** [comment]
Thanks Jakub, I switched to stable and will test again. Great job!
