### ISSUE TITLE
Incompatible with firebase_messaging

### ISSUE THREAD

**Issue by Froelund** [jhomlala/catcher#34]
Great library! However, when using it with `firebase_messaging` you are unable to receive push notifications. This is due to an [issue](https://github.com/MaikuB/flutter_local_notifications/issues/111) with the dependency `flutter_local_notifications`.

**Comment by Froelund** [comment]
I suggest you consider splitting up the library, so developers could use the core functionality without having to depend on libraries they don't use.

`catcher`
`catcher_notifications`
`catcher_http`
etc...

**Comment by Rodiii** [comment]
Indeed, that's an awesome library.

Anyhow, I'm also affected by the firebase_messaging incompatibility. Any chance for a fix?

**Comment by Dviejopomata** [comment]
First of all, thanks for developing this library.

Since I was using catcher and firebase_messaging wasn't compatible, I made a fork to remove completely the flutter_local_notifications and i had to add the dependency as a git URL in the project pubspec.yaml.

```yaml
  catcher:
    git:
      url: git://github.com/Dviejopomata/catcher.git
```
It's not the best solution, but if you have to solve it without changing any code it works.

**Comment by GrahamDi** [comment]
@Froelund @Dviejopomata @Rodiii @jhomlala 
FCM messaging is working fine in my app with Catcher. I get the notification for onMessage, onResume and onLaunch. It appears to be related to the inclusion of the following statement:

`WidgetsFlutterBinding.ensureInitialized();`

just before:

 `catcher = Catcher(
    MyApp(catcherCustomParameters),
    debugConfig: debugOptions,
    profileConfig: profileOptions,
    releaseConfig: releaseOptions,
  );`

Not sure if this works for you and definitely have no idea why it works for me but thought I would mention it.

**Comment by alby97** [comment]
Hi, there isn't any other solution about this dependency problem?

**Comment by jhomlala** [comment]
Fixed in https://github.com/jhomlala/catcher/commit/6595abe8980f37256ba5c0b884f652330499b264
