### ISSUE TITLE
How can I report error to slack channel?

### ISSUE THREAD

**Issue by hasimyerlikaya** [jhomlala/catcher#36]
Hi,

I want to report an error to the Slack channel.
I think it needs to be a custom handler.
How can I deal with this?

**Comment by MozesMa** [comment]
you can use Http Handler and post to a webhook:
https://api.slack.com/incoming-webhooks

**Comment by jhomlala** [comment]
Check slack handler:
https://github.com/jhomlala/catcher#slack-handler

**Comment by hasimyerlikaya** [comment]
@MozesMa  and @jhomlala  Thank you very much.
