### ISSUE TITLE
How to dynamically add customparams to the crash report 

### ISSUE THREAD

**Issue by praveenb** [jhomlala/catcher#37]
Hi,
Thank you so much for the wonderful plugin.

As per the plugin details, i need to set CatcherOptions at the beginning in the main.dart file. 

But, I need to add some more data to customParameters based on user details. Any way to add data to the Customparams data. 

Please let me know on it.

Thank you.

**Comment by jhomlala** [comment]
Please upgrade to Catcher 0.2.1. Also check this example: https://github.com/jhomlala/catcher/blob/master/example/lib/change_custom_parameters_example.dart

**Comment by ariefwijaya** [comment]
I got this error

> Please upgrade to Catcher 0.2.1. Also check this example: https://github.com/jhomlala/catcher/blob/master/example/lib/change_custom_parameters_example.dart

I got this error when I was trying this example 
```
Cannot set value in unmodifiable Map
```
