### ISSUE TITLE
Catcher.addDefaultErrorWidget is overflowing

### ISSUE THREAD

**Issue by narayanansampath** [jhomlala/catcher#42]
![Screenshot_20190902-183147](https://user-images.githubusercontent.com/19869271/64117759-a43fde80-cdb3-11e9-9691-a811aaedea33.png)

default errorscreen widget is not working as expected. I used the code exactly as mentioned in the example.

**Comment by jhomlala** [comment]
Can you share your code?

**Comment by narayanansampath** [comment]
This is my main.dart file
```
@override
  Widget build(BuildContext context) {
    return MaterialApp(
      navigatorKey: Catcher.navigatorKey,
      builder: (BuildContext context, Widget widget) {
        Catcher.addDefaultErrorWidget(
            showStacktrace: true,
            customTitle: "There was an unexpected error in the application, please restart and login again",
            customDescription: "Looks like the app had an unexpected error, please reach out to the developer if the problem persists.";
        return widget;
      },
  }
```

**Comment by kabnfever** [comment]
In addition it should be noted that even when setting "showStacktrace: **true**" in the above example the stack trace is NOT shown in error dialog.  Please correct this as well.

**Comment by narayanansampath** [comment]
Thank you. I'll close this issue now.

**Comment by kabnfever** [comment]
Maybe I missed something, but isn't this still an issue?  Catcher is stall at version 0.2.4 and our 2 issues on this thread have not been corrected as far as I can tell.

**Comment by narayanansampath** [comment]
I thought it was occuring because of some error on my side and I ended up designing my own error screen. Although my implementation looks correct as per the example, so I'm reopening this issue.

**Comment by kabnfever** [comment]
Thx for reopening.  Funny, I did the same thing...created my own "catch all" app-crash error dialog...but I hate to do a homegrown workaround on an otherwise great package.

**Comment by jhomlala** [comment]
I have probably found fix for this problem. Please check Catcher 0.2.7 and confirm if same problem still occurs.
Thanks!
