### ISSUE TITLE
Dio version issue

### ISSUE THREAD

**Issue by jasonlaw** [jhomlala/catcher#43]
There is a breaking change in Dio package in version 2.2.1.
Whenever I get the latest, the Dio version 2.2.1 will be downloaded and there will be an error in Catcher due to the breaking change in Dio.

![image](https://user-images.githubusercontent.com/107820/65128048-47872980-da2b-11e9-9ccd-90f142a26b67.png)

**Comment by jasonlaw** [comment]
Here is the error:

![image](https://user-images.githubusercontent.com/107820/65129644-51f6f280-da2e-11e9-9462-3824d462caa2.png)

**Comment by jhomlala** [comment]
Fixed
