### ISSUE TITLE
No named parameter with the name 'connectTimeout'.

### ISSUE THREAD

**Issue by praveenb** [jhomlala/catcher#44]
Hi @jhomlala ,
After upgrading plugins, app getting below Compile error.
```
`Compiler message:
/C:/Users/.../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/catcher-0.2.3/lib/handlers/http_handler.dart:41:19: Error: No named parameter with the name 'connectTimeout'.
          Options(connectTimeout: requestTimeout, headers: headers);
                  ^^^^^^^^^^^^^^
/C:/Users/.../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/dio-2.2.1/lib/src/options.dart:139:3: Context: Found this candidate, but the arguments don't match.
  Options({
  ^

Compiler failed on E:\ASW\app_flutter_local\lib\main.dart
Finished with error: Gradle task assembleDebug failed with exit code 1`
```

We see its due to recent code changes in dio plug in options.dart file. Please fix this issue in http_handler.dart file, to use latest method in dio plugin.

Thank you.

**Comment by StanislavBondar** [comment]
Reached the same compiler error. Temporary modifying `http_handler.dart:41:19`  with
`Options options =
          Options(sendTimeout: requestTimeout, receiveTimeout: requestTimeout, headers: headers);`

Hope for an early update.

Thank you.

**Comment by jhomlala** [comment]
Fixed
