### ISSUE TITLE
Please upgrade dependencies to use dio package 3.x.x

### ISSUE THREAD

**Issue by kabnfever** [jhomlala/catcher#46]
The latest Dio package published today (9/18/2019) on GitHub and pub.dev is now version 3.0.0.  The Dio folks implemented some changes that my team who work for the state of California would like to implement.  When trying to perform a "flutter packages get" after updating our Flutter/Dart pubspec.yaml to use "dio: 3.0.0" we receive the following failure:

**[ctma.R204-error-handling-p1.as] flutter packages get
Running "flutter pub get" in ctma.R204-error-handling-p1.as...     
Because catcher 0.2.4 depends on dio ^2.1.16 and calapp depends on dio ^3.0.0, catcher 0.2.4 is forbidden.

So, because calapp depends on catcher 0.2.4, version solving failed.
pub get failed (1)
exit code 1**

Thanks in advance.

**Comment by vico-aguado** [comment]
Same problem :(

**Comment by benoitskipr** [comment]
#51

**Comment by jhomlala** [comment]
Fixed in 0.2.5
