### ISSUE TITLE
 Suggestion on allow decoration to DialogReportMode and allow CustomReportMode

### ISSUE THREAD

**Issue by RaashVision** [jhomlala/catcher#47]
Hi Thiyraash here,first of all thanks alot for the library! This library is so good and helpful to log error. I have suggestion regarding the library. Why not you allowed developer to create and add their custom report mode ? This feature can give them more flexibility for them to even use custom dialogs with decoration. Just my suggestion, correct me if I'm wrong.

**Comment by jhomlala** [comment]
Please check this example: https://github.com/jhomlala/catcher/blob/master/example/lib/custom_report_mode_example.dart

You can create new custom report mode by yourself with Catcher 0.2.6
