### ISSUE TITLE
Portuguese adjustments

### ISSUE THREAD

**Issue by egorges** [jhomlala/catcher#49]
Small corrections are needed in Portuguese on Catcher 0.2.4:

Please update buildDefaultPortugueseOptions() to:
        notificationReportModeTitle: "Erro de aplicação",
(current has an ending "d")

        dialogReportModeTitle: "Erro",
        pageReportModeTitle: "Erro",
(current is "Batido" which is the Crashed translation in case of car crash, or  a milk shake, but not used on System errors)

        dialogReportModeDescription:
        pageReportModeDescription:
Please include an "s" on the 2nd "relatório de erro", making it equal to the 1st "relatório de erros"

Thanks!

**Comment by jhomlala** [comment]
Fixed in 0.2.5. Thank you :)
