### ISSUE TITLE
How to handle exception thrown while entering in a new page?

### ISSUE THREAD

**Issue by davidobber** [jhomlala/catcher#50]
I'm new to Flutter, so maybe this is a dummy question. Anyway, I'm trying to understand how to use this great library to handle errors. I'm stucked with this scenario. Suppose you have two different pages, i.e. list & detail. When the user selects an item in the list, the detail screen should appear. But in its build method, something throws an exception. As long as I haven't nothing to show in the detail screen, due to the exception, I would like to show a PageReport and then, when the user accepts/rejects the request to send it, I want to go back to the list. But PageReport uses Navigator.push()  and it tries to go back to the "empty detail window".

So I solved the problem extending PageReportMode to override reqyestAction and call the pushReplacement method.

```dart
class MyPageReportMode extends PageReportMode {

  MyPageReportMode({showStackTrace}): super(
      showStackTrace: showStackTrace,
  );

  @override
  void requestAction(Report report, BuildContext context) {
    _navigateToPageWidget(report, context);
  }

  _navigateToPageWidget(Report report, BuildContext context) async {
    print("_navigateToPageWidget.pushReplacement");
    await Future.delayed(Duration.zero);
    Navigator.pushReplacement(
      context,
      MaterialPageRoute(builder: (context) => PageWidget(this, report)),
    );
  }
}
```

Is there a better and simple approach?

**Comment by jhomlala** [comment]
Please check this example: https://github.com/jhomlala/catcher/blob/master/example/lib/custom_report_mode_example.dart

You can create your own page report mode since Catcher version 0.2.6.

**Comment by davidobber** [comment]
Thank you for your quick reply.

Unfortunately, I tried the example but it throws an exception.

I/flutter ( 3629): [2019-10-10 08:58:08.184954 | Catcher | FINE] Using
debug config
I/flutter ( 3629): [2019-10-10 08:58:08.946515 | Catcher | FINE] Catcher
configured successfully.
E/flutter ( 3629): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled
Exception: NoSuchMethodError: The method 'ancestorStateOfType' was called
on null.
E/flutter ( 3629): Receiver: null
E/flutter ( 3629): Tried calling: ancestorStateOfType(Instance of
'TypeMatcher<NavigatorState>')
E/flutter ( 3629): #0      Object.noSuchMethod
(dart:core-patch/object_patch.dart:51:5)
E/flutter ( 3629): #1      Navigator.of
(package:flutter/src/widgets/navigator.dart:1472:19)
E/flutter ( 3629): #2      Navigator.push
(package:flutter/src/widgets/navigator.dart:1107:22)
E/flutter ( 3629): #3      CustomPageReportMode._navigateToPageWidget
(package:flutter_app/widgets/main_custom_exception_page.dart:61:15)

It seems that the wrong context is passed to the widget.


Il giorno mer 9 ott 2019 alle ore 22:20 Jakub <notifications@github.com> ha
scritto:
