### ISSUE TITLE
LocalizationOptions settings are being ignored

### ISSUE THREAD

**Issue by kabnfever** [jhomlala/catcher#53]
The Catcher class is called from the main() function of a Flutter app.  The main() function of a Flutter app has no BuildContext which causes the Catcher class to fail to initialize the Catcher private _localizationOptions map to use the custom localization values passed in the debug and release option params.  All Catcher dialogs then fail to use the custom localization text.

My debugging research has found that the Catcher private function named _setupLocalization() is checking for a valid BuildContext (_isContextValid()) in order to populate the private _localizationOptions map.  However, because a Flutter main() function has no context at startup, the Catcher private function _setupLocalization() never uses the custom LocalizationOptions defined in either the debugConfig or the releaseConfig params passed into the Catcher class instance.

I would love to change this code and create a pull request for you, but unfortunately I do not understand your intent of using a BuildContext during the startup of the app when no BuildContext is available yet.

I've attached a main.dart file (_renamed main.txt due to limitations of GitHub_) which is nearly an exact copy of the Catcher example file named localization_example.dart.  The only thing I changed was to remove the PL localization options and I modified the EN localization content declaration, all functionality is identical to the Catcher example file.

**_Here's my sample file for you to test (my custom localization content is not displayed):_**
[main.txt](https://github.com/jhomlala/catcher/files/3710325/main.txt)
- Just rename this to main.dart, create a Flutter project, then copy it on top of the default main.dart. Then add the following dependencies to your pubspec.yaml:
**catcher: ^0.2.7
easy_localization: ^1.3.1**

**Comment by GrahamDi** [comment]
I am experiencing the same issue. I had used LocalizationOptions to change the dialogue content to something I preferred. It has now gone back to the default since I upgraded Flutter and Catcher (to 0.2.7).
A couple of (dumb) questions:
Is there not a more elegant way of changing the dialogue text other than using localizations? It feels like a workaround rather than a legitimate feature of Catcher.
Whatever localizations are done have to be duplicated for CatcherOptions Debug, Profile and Release. I want my app to support 17 languages so this is a lot of duplication and boilerplate.
Finally, I make use of the Android Studio Flutter_i18n plugin and localization mechanism which is pretty slick. With Catcher, I now have to use a 'second' localisation process where I list 'en', 'es', 'jp', etc. location text translations in main.dart. Lots of extra code that I would like to see 'folded' into a more mainstream localization process.

**Comment by jhomlala** [comment]
@kabnfever I've used your code and it's all fine. It shows me dialog with texts from your LocalizationOptions object.
![image](https://user-images.githubusercontent.com/1329033/66715225-df74fa80-edc0-11e9-9afc-5afa2989aba1.png)

**Comment by jhomlala** [comment]
@GrahamDi Currently, LocalizationOptions is the only way to setup translations in Catcher.  If your LocalizationOptions has too much code, then move it to another 'helper' class which will provide translations for Catcher. 

```
class LocalizationHelper{
  static List<LocalizationOptions> provideLocalizationOptions(){
   //build here your localizaiton options
  }
}
```

```
  CatcherOptions debugOptions = CatcherOptions(DialogReportMode(), [
    ConsoleHandler(),
    HttpHandler(HttpRequestType.post, Uri.parse("https://httpstat.us/200"),
        printLogs: true)
  ], localizationOptions: LocalizationHelper.provideLocalizationOptions());


```

**Comment by GrahamDi** [comment]
Ok, thanks Jakub. I will do as you suggest.

**Comment by kabnfever** [comment]
We have multiple machines here in the Calif Dept of Corrections & Rehabilitation which no longer have the localization text (_a very small set of text_) that was previously working before the latest Catcher rev.  

There is no BuildContext in main(), so there is no way the Catcher isContextValid() function can succeed.  I have debugged the Catcher code repeatedly to the same result. I have fixed the Catcher code in function _setupLocalization() in a forked local copy and now it works correctly.

@jhomlala I'm sure you have already tested this, but just just in case before you try another test, do not build from your local machinie where you are maintaining the Catcher code.  Go to a machine or VM that does not have Catcher on it, do a "flutter clean" and then build/run the test/example app, so that way you are pulling in the public Catcher code like the rest of us.

Just in case you need it, here's my Flutter Doctor info:

**Doctor summary (to see all details, run flutter doctor -v):**
[√] Flutter (Channel dev, v1.10.14, on Microsoft Windows [Version 10.0.18362.418], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[√] Android Studio (version 3.5)
[√] VS Code, 64-bit edition (version 1.39.0)
[√] Connected device (2 available)

• No issues found!

**Comment by jhomlala** [comment]
@kabnfever Why are you using unstable version of Flutter (dev channel)?
I'm using stable version: Channel stable, v1.9.1+hotfix.4,

**Comment by kabnfever** [comment]
Hey @jhomlala, great point. We are using the Flutter dev branch due to certain of our devices that have an older GPU which the current stable branch does not properly support (see https://github.com/flutter/flutter/issues/40150), but the dev branch does support it.  However, as you already know the dev branch can be a bit buggy and case in point noted here...

I tested both the stable and dev Flutter branches to be sure and of course Catcher localization text renders properly in the stable branch as you have noted...thank you for pointing that out!  

In debug I have found that in the catcher.dart function _setupErrorHooks() where the call to runApp(rootWidget) occurs, the Flutter dev branch does not initialize the currentState element of the global navigatorKey, but the stable branch does.  Oh well, so much for living on the bleeding edge :(.  We will adjust accordingly.

**Comment by GrahamDi** [comment]
@kabnfever @jhomlala 
Me again. My dialogues are once again ignoring my localizations and showing the default 'Crash' dialogue. Are you experiencing this? 
I am using:
```
Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.19536.1000], locale en-GB)
```
