### ISSUE TITLE
Execute code when exception is thrown?

### ISSUE THREAD

**Issue by nt4f04uNd** [jhomlala/catcher#54]
Sorry for a dumb question, but I can't find this in your docs. Consider I have a music player - how to execute e.g. my pause function, when error is thrown?

**Comment by jhomlala** [comment]
You can create custom handler which will pause your music player. To create custom handler you need to extend ReportHandler class. See simple report handler here: https://github.com/jhomlala/catcher/blob/master/lib/handlers/toast_handler.dart
