### ISSUE TITLE
EmailManualHandler does not work correct with Microsoft Outlook on Android.

### ISSUE THREAD

**Issue by fkranenburg** [jhomlala/catcher#57]
We use the EmailManualHandler and on Android the handler works fine, but not with all e-mail handlers. In the Yahoo mail app and Gmail mail app the catcher mail is correctly composed, but when we use Microsoft Outlook as the mail app, the composed mail is missing all the html inside the mail body.

We tried this on several different phones, all same result.

How can we fix this? Or is there some way to add these logs as a seperate attachment?

```
    var emailManualHandler = EmailManualHandler(["support@xxxx"],
      enableDeviceParameters: true,
      enableStackTrace: true,
      enableCustomParameters: true,
      enableApplicationParameters: true,
      sendHtml: true,
      emailTitle: "App crash report",
      emailHeader: "app",
      printLogs: true,);
    return CatcherOptions(DialogReportMode(), [emailManualHandler],
        localizationOptions: [getDutchLocale()],
        handlerTimeout: 10000,
        customParameters: {"appdomain": app.url});
```

**Comment by jhomlala** [comment]
Just quickly looked into this problem, and seems like outlook is bugged. What you need to do is create new report mode which will create file  - see FileHandler (https://github.com/jhomlala/catcher/blob/master/lib/handlers/file_handler.dart) and then check how EmailManualHandler works (https://github.com/jhomlala/catcher/blob/master/lib/handlers/email_manual_handler.dart). There are MailOptions which can get attachements parameter.

**Comment by fkranenburg** [comment]
Thanks! While this could work we decided not to implement this ourself for now. Hopefully Microsoft will fix this issue soon.
