### ISSUE TITLE
Email Handler - Email Sign-in Attempt Blocked by Google.

### ISSUE THREAD

**Issue by GrahamDi** [jhomlala/catcher#58]
Hi Jakub,

I make use of EmailHandler to automatically send emails when errors occur. I set up a Gmail account (linked to my main account), as you suggest, and use its address and password in the app as the sender of the emails. All works fine as far as Catcher is concerned...has been very useful in my testing/debugging.

However, a friend of mine is now testing the app some 9000kms from me. When she hit a bug and the error was caught by Catcher, the sending of the email failed because Google detected it as a suspicious login to the email account and blocked it. Obviously, this is going to be a big problem when the app goes live. I am using Firebase as a backend and have no plans to set up my own server so HTTP handler is a no-go. 

I see Catcher as a very important component of my live app and really hope there is a solution.
Do you have any advice on how to overcome this issue?

**Comment by jhomlala** [comment]
Hi @GrahamDi  as I understand, you are using email auto handler. You should use this handler only for testing it with your developer devices. Since your friend is 9k km from you, I suggest using email manual handler which will open default email application installed in friend's device. Your friend just need to hit send button and that's all!

**Comment by GrahamDi** [comment]
Hi Jakub,

Thanks for getting back to me. OK, I will have to go that route though it
is not ideal as I wanted to use silent error reporting when I go live. I am
concerned that 'manual' error reporting by the user will have a negative
impact on their perception of the app.

Krgrds, Graham

+27 84 798 6450

**Comment by GrahamDi** [comment]
One last question, Jakub. 

Is there a way of localizing the `emailTitle ` and `emailHeader` texts  that are used by `EmailManualHandler`?

**Comment by jhomlala** [comment]
Why do you need to localize email title and email header? This email report is intended to be received by admin, so I think english language will be enough.

**Comment by GrahamDi** [comment]
Hi Jakob,

Yes, but because we cannot use 'silent' email error reporting, the user will see the email being 'built' because it has to be sent via his/her own email client on the device. It then makes sense that maybe the title, but definitely the introductory heading, for the email are in the user's own language so that they are clear on what is being sent.

**Comment by jhomlala** [comment]
Hi GrahamDi, here is example based on EmailManualHandler. You need to copy rest of EmailManualHandler, but it won't be hard.

`import 'package:flutter/material.dart';
import 'package:catcher/catcher_plugin.dart';
import 'package:flutter_mailer/flutter_mailer.dart';

main() {
  GlobalKey<NavigatorState> navigatorKey = new GlobalKey<NavigatorState>();
  CatcherOptions debugOptions = CatcherOptions(
      DialogReportMode(), [TranslatedEmailManualHandler(navigatorKey)]);
  CatcherOptions releaseOptions = CatcherOptions(PageReportMode(), [
    EmailManualHandler(["recipient@email.com"])
  ]);

  Catcher(MyApp(navigatorKey),
      debugConfig: debugOptions,
      releaseConfig: releaseOptions,
      navigatorKey: navigatorKey);
}

class MyApp extends StatefulWidget {
  final GlobalKey<NavigatorState> navigatorKey;

  const MyApp(this.navigatorKey);

  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      navigatorKey: widget.navigatorKey,
      home: Scaffold(
          appBar: AppBar(
            title: const Text('Plugin example app'),
          ),
          body: ChildWidget()),
    );
  }
}

class ChildWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
        child: FlatButton(
            child: Text("Generate error"), onPressed: () => generateError()));
  }

  generateError() async {
    Catcher.sendTestException();
  }
}

class TranslatedEmailManualHandler extends ReportHandler {
  final GlobalKey<NavigatorState> navigatorKey;

  TranslatedEmailManualHandler(this.navigatorKey);

  @override
  Future<bool> handle(Report report) async {
    BuildContext context = navigatorKey.currentState.overlay.context;
    Locale locale = Localizations.localeOf(context);
    String countryCode = locale.countryCode;
    print("My country code: " + countryCode);
    _sendEmail(report, countryCode);

    return true;
  }

  Future<bool> _sendEmail(Report report, String countryCode) async {
    String body ="";
    String title ="";
    if (countryCode == "US"){
      body = "English body. You should copy everything from email manual handler.";
      title = "English title";
    }


    try {
      final MailOptions mailOptions = MailOptions(
        body: body,
        subject: title,
        recipients: ["example@email.com"],
        isHTML: false,
      );
      await FlutterMailer.send(mailOptions);
      print("Email sent!");
      return true;
    } catch (exc, stackTrace) {
      print(exc);
      return false;
    }
  }
}
`

**Comment by jhomlala** [comment]
Remember to use latest Catcher version released today.

**Comment by GrahamDi** [comment]
@jhomlala Thanks a lot, Jakub. I will work through it tomorrow and will update Catcher version as you recommend.
