### ISSUE TITLE
Allow setting custom navigatorKey

### ISSUE THREAD

**Issue by kuhnroyal** [jhomlala/catcher#60]
It would be great if we could set a custom `GlobalKey<NavigatorState> navigatorKey` which defaults to the existing one if not provided. This would make it easier to integrate Catcher with other libraries that also rely on the navigator key.

**Comment by jhomlala** [comment]
Thank you for your idea. Please check next Catcher release.
https://github.com/jhomlala/catcher/commit/ca92b015a22c1fdfc5b96a55ef1b317934c59dea
