### ISSUE TITLE
Error Widget does not render correctly in dialog

### ISSUE THREAD

**Issue by salsolatragus** [jhomlala/catcher#62]
When I add Catcher's error widget to my app, I correctly see this widget when an error occurs while building the main widgets. However, when an error occurs while building a dialog, the widget doesn't seem to render correctly. Below are screenshots of the dialog without and with the error widget installed:

<img width="343" alt="Screenshot 2019-11-28 21 22 21" src="https://user-images.githubusercontent.com/154050/69830488-51948800-1225-11ea-86da-e0e632f47f40.png">

<img width="326" alt="Screenshot 2019-11-28 21 22 33" src="https://user-images.githubusercontent.com/154050/69830492-53f6e200-1225-11ea-859f-9c79dd320fdc.png">

**Comment by jhomlala** [comment]
Hi, can you share your example? I can't reproduce it.

**Comment by salsolatragus** [comment]
I'll try to produce a minimal example.

**Comment by salsolatragus** [comment]
Sorry for the late reply.

I tried to reproduce this again. The white screen still happens when the error is thrown while building an element of a `ListView` or `Column`. The cause seems to be that flutter assigns an infinite size to the element then, which pushes everything else off the screen.

This looks the same now, however, regardless of whether I activate the Catcher error widget or not, so the problem seems unrelated to Catcher.

**Comment by jhomlala** [comment]
This should be fixed now.

**Comment by salsolatragus** [comment]
Thanks for letting me know!
