### ISSUE TITLE
Using Catcher with flutter_bloc causes infinite report loop

### ISSUE THREAD

**Issue by salsolatragus** [jhomlala/catcher#63]
I have an app that uses `flutter_bloc` for state management and `Catcher` for error reporting.

When an exception is thrown in a `BlocBuilder`'s `builder` method (with `PageReportMode` enabled), Catcher opens the report page infinitely many times, because apparently the builder keeps rebuilding. I'm not 100% sure whose at fault here, but I experienced this issue with Catcher's navigation only.

Here's a [screen capture showing the behavior](https://github.com/jhomlala/catcher/files/3907535/Error_Catcher_flutter_bloc.mov.zip).

Here's the corresponding [minimal example](https://gist.github.com/salsolatragus/ac66e1808d4ccc43acf2d8735f97cf5a).

Let me know if I can do anything to help debug this. I'm not flutter savvy enough for such kinds of problems... not even sure where to start, honestly.

**Comment by jhomlala** [comment]
Hi, I've just tested your code and page has opened only 1 time. Can you share your flutter doctor? Are you using flutter stable version?

**Comment by salsolatragus** [comment]
It did happen with 1.9.1, it no longer seems to happen after update to 1.12.13.
