### ISSUE TITLE
I get the connection from httphandler but nothing comes in the request

### ISSUE THREAD

**Issue by ederluca** [jhomlala/catcher#66]
Good afternoon

Guys I have a little problem with catcher and I can not solve I declared my main function as follows in my project:

void main () {
  CatcherOptions debugOptions = CatcherOptions (
    SilentReportMode (),
    [
      ConsoleHandler (),
      HttpHandler (HttpRequestType.post,
          Uri.parse ("http://192.168.0.11/api/appErros.php"),
          headers: {"header": "value"}, requestTimeout: 4000, printLogs: true)
    ],
  );
  CatcherOptions releaseOptions = CatcherOptions (
    SilentReportMode (),
    [
      ConsoleHandler (),
      HttpHandler (HttpRequestType.post,
          Uri.parse ("http://192.168.0.11/api/appErros.php"),
          headers: {"header": "value"}, requestTimeout: 4000, printLogs: true)
    ],
  );

  Catcher (MyApp (), debugConfig: debugOptions, releaseConfig: releaseOptions);
}

I get the request in my api but when I debug my php to check what information he sent in the post to the $ _POST variable that gets this request says it is blank I don't understand what I'm doing wrong below follows a test project I created To understand how the plugin works:

import 'package: flutter / material.dart';
import 'package: catcher / catcher_plugin.dart';

void main () {
  CatcherOptions debugOptions = CatcherOptions (
    SilentReportMode (),
    [
      ConsoleHandler (),
      HttpHandler (HttpRequestType.post,
          Uri.parse ("http://192.168.0.11/api/appErros.php"),
          headers: {"header": "value"}, requestTimeout: 4000, printLogs: true)
    ],
  );
  CatcherOptions releaseOptions = CatcherOptions (
    SilentReportMode (),
    [
      ConsoleHandler (),
      HttpHandler (HttpRequestType.post,
          Uri.parse ("http://192.168.0.11/api/appErros.php"),
          headers: {"header": "value"}, requestTimeout: 4000, printLogs: true)
    ],
  );

  Catcher (MyApp (), debugConfig: debugOptions, releaseConfig: releaseOptions);
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState () => _MyAppState ();
}

class _MyAppState extends State <MyApp> {
  @override
  void initState () {
    super.initState ();
  }

  @override
  Build widget (BuildContext context) {
    return MaterialApp (
      navigatorKey: Catcher.navigatorKey,
      home: MyHomePage (title: 'Flutter Demo Home Page'),
    );
  }
}

generateError (String page, String Step) async {
  throw page + "Step:" + step.toString ();
}

/ * class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Build widget (BuildContext context) {
    return MaterialApp (
      title: 'Flutter Demo',
      theme: ThemeData (
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage (title: 'Flutter Demo Home Page'),
    );
  }
} * /

class MyHomePage extends StatefulWidget {
  MyHomePage ({Key key, this.title}): super (key: key);

  final String title;

  @override
  _MyHomePageState createState () => _MyHomePageState ();
}

class _MyHomePageState extends State <MyHomePage> {
  int _counter = 0;

  void _incrementCounter () {
    setState (() {
      _counter ++;
    });
  }

  @override
  Build widget (BuildContext context) {
    return Scaffold (
      appBar: AppBar (
        title: Text (widget.title),
      ),
      body: Center (
        child: Column (
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget> [
            Text (
              'You have pushed the button this many times:',
            ),
            Text (
              '$ _counter',
              style: Theme.of (context) .textTheme.display1,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton (
        onPressed: () {
          generateError ('Home', 'Test');
          // throw 'Error';
        },
        tooltip: 'Increment',
        child: Icon (Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

**Comment by jhomlala** [comment]
Hi, here is example backend in Java: https://github.com/jhomlala/catcher/tree/master/backend.
Data is send as Json in given structure:
```class Report {
  final dynamic error;
  final dynamic stackTrace;
  final DateTime dateTime;
  final Map<String, dynamic> deviceParameters;
  final Map<String, dynamic> applicationParameters;
  final Map<String, dynamic> customParameters;

  Report(this.error, this.stackTrace, this.dateTime, this.deviceParameters,
      this.applicationParameters, this.customParameters);

  Map<String, dynamic> toJson() => {
        "error": error.toString(),
        "stackTrace": stackTrace.toString(),
        "deviceParameters": deviceParameters,
        "applicationParameters": applicationParameters,
        "customParameters": customParameters,
        "dateTime": dateTime.toIso8601String()
      };
}
```
