### ISSUE TITLE
WidgetsFlutterBinding.ensureInitialized() -> error dialog doesn't show up 

### ISSUE THREAD

**Issue by te8uekm12** [jhomlala/catcher#68]
Catcher doesn't show up an error dialog when I call WidgetsFlutterBinding.ensureInitialized(); in my app's main function. Here is an example based on your's "Basic Example".

`**Future<void> main()  async {
  WidgetsFlutterBinding.ensureInitialized();**
  CatcherOptions debugOptions =
  CatcherOptions(DialogReportMode(), [ConsoleHandler()]);
  CatcherOptions releaseOptions = CatcherOptions(DialogReportMode(), [
    EmailManualHandler(["recipient@email.com"])
  ]);

  Catcher(MyApp(), debugConfig: debugOptions, releaseConfig: releaseOptions);
}

class MyApp extends StatefulWidget {
....
`

**Comment by jamesdixon** [comment]
Did you ever get this working?

**Comment by GrahamDi** [comment]
@te8uekm12 @jamesdixon @jhomlala 
The error dialogue is working for me (albeit without being localized, which is another issue #71) and I use `WidgetsFlutterBinding.ensureInitialized();`. 

The main differences I can see between your code and mine are as follows:

- I create a Catcher object in main.dart immediately after the imports: `Catcher catcher;`
- I set a global navigator key before calling `WidgetsFlutterBinding.ensureInitialized();`: 
`GlobalKey<NavigatorState> navigatorKey = GlobalKey<NavigatorState>();`
- I use that key when assigning `catcher`:
```
catcher = Catcher(
    MyApp(navigatorKey, globals.catcherCustomParameters),
    debugConfig: debugOptions,
    profileConfig: profileOptions,
    releaseConfig: releaseOptions,
    navigatorKey: navigatorKey,
  );
```
Hope that helps you.

**Comment by jhomlala** [comment]
Issue is connected with this bug: https://github.com/flutter/flutter/issues/39494
Let's wait for Flutter team to fix this. If you don't need, please don't use WidgetsFlutterBinding.ensureInitialized(); before Catcher.

You can use WidgetsFlutterBinding.ensureInitialized(); after Catcher creation:
```Catcher(MyApp(), debugConfig: debugOptions, releaseConfig: releaseOptions);
  WidgetsFlutterBinding.ensureInitialized();```

**Comment by javadkt** [comment]
fwf
