### ISSUE TITLE
Allow using custom SentryClient in SentryHandler

### ISSUE THREAD

**Issue by kuhnroyal** [jhomlala/catcher#69]
In my case a require the `SentryClient` to use a custom Http client and the `SentryClient` is only available lazily by some form of dependency injection.

It would be great if the `SentryHandler` exposes an async getter for the `SentryClient` that can be overridden by extending the class and an alternative constructor that does not require the client to be available.

**Comment by jhomlala** [comment]
Fixed in 0.3.0 Release
