### ISSUE TITLE
Only Handles Async Exceptions?

### ISSUE THREAD

**Issue by iqbalmineraltown** [jhomlala/catcher#75]
Hi, thanks for creating useful plugin!
Does this plugin only handles exceptions which thrown from `async` function?

This is how I reproduced the issue:
```
void main() {
  CatcherOptions debugOptions = CatcherOptions(PageReportMode(), [
    EmailManualHandler(['debug@mail.com'])
  ]);
  CatcherOptions releaseOptions = CatcherOptions(DialogReportMode(), [
    EmailManualHandler(['release@mail.com'])
  ]);

  Catcher(MyAppDemo(),debugConfig: debugOptions, releaseConfig: releaseOptions);
}

class MyAppDemo extends StatelessWidget {
  void _generateErrorAsync() async {
    Catcher.sendTestException();
  }

  void _generateErrorSync() {
    Catcher.sendTestException();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      navigatorKey: Catcher.navigatorKey,
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Plugin example app'),
        ),
        body: Container(
          child: FlatButton(
            child: Text("Generate error"),
            onPressed: () => _generateErrorSync(),
            // onPressed: () => _generateErrorAsync(),
          ),
        ),
      ),
    );
  }
}
```

Using `_generateErrorAsync` would show page report mode as basic example
using `_generateErrorSync` would show the following on console:
```
Restarted application in 1,774ms.
flutter: [2020-02-07 14:21:36.854522 | Catcher | FINE] Using debug config
flutter: [2020-02-07 14:21:36.939119 | Catcher | FINE] Catcher configured successfully.

[38;5;248m════════ Exception caught by gesture ═══════════════════════════════════════════[39;49m
[38;5;244mThe following FormatException was thrown while handling a gesture:[39;49m
Test

[38;5;244mWhen the exception was thrown, this was the stack[39;49m
[38;5;248m#0      Catcher.sendTestException[39;49m
[38;5;248m#1      MyAppDemo._generateErrorSync[39;49m
[38;5;248m#2      MyAppDemo.build.<anonymous closure>[39;49m
[38;5;244m#3      _InkResponseState._handleTap[39;49m
[38;5;244m#4      _InkResponseState.build.<anonymous closure>[39;49m
[38;5;244m...[39;49m
[38;5;244mHandler: "onTap"[39;49m
[38;5;244mRecognizer: TapGestureRecognizer#44e47[39;49m
    [38;5;244mdebugOwner: GestureDetector[39;49m
    [38;5;244mstate: possible[39;49m
    [38;5;244mwon arena[39;49m
    [38;5;244mfinalPosition: Offset(59.0, 121.5)[39;49m
    [38;5;244mfinalLocalPosition: Offset(64.5, 18.0)[39;49m
    [38;5;244mbutton: 1[39;49m
    [38;5;244msent tap down[39;49m
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m
```

Thanks!

**Comment by jhomlala** [comment]
Unfortunately exceptions caught by gesture, can't be catched by Catcher.

**Comment by jhomlala** [comment]
I leave this issue open, maybe I'll find solution in future.

**Comment by codegrue** [comment]
I wonder if there is a relation to this post, where it appears more errors are caught in Release than in Debug:

https://stackoverflow.com/questions/57879455/flutter-catching-all-unhandled-exceptions

I'm going to experiment with a real device to see if the behavior changes.

**Comment by codegrue** [comment]
With further testing, I had a callback that was async and Catcher was missing this. I rearchitected it to pass the function down to make it synchronous, and now it's working. May help others... I think in the original post async is issue, not sync.

**Comment by jhomlala** [comment]
@codegrue I've tested sync error in release mode and catcher has caught it. So it seems exceptions are not caught by gesture in release mode. So you can use Catcher and it will work in release mode correctly.

**Comment by javierforero** [comment]
@codegrue having the same issues where async is uncaught for me. Could you provide a more detailed explanation on how rearchitected to make yours work?

**Comment by codegrue** [comment]
I didn't do anything different. It seems like on a device or sometimes in an emulator the exceptions bubble up correctly. If they stop working I restart the emulator.

**Comment by prondzyn** [comment]
Is there any option to "programmatically" generate the report? I have probably the same problem - error which is "packed" with gesture is not handled by Catcher. All others are correctly handled. I wonder if I would be able to catch the unhandled error in `.catchError` (I am able to do that) and then just do something like `Catcher.generateReport`. Is it doable? Or would it be much work to introduce such functionality?

**Comment by jhomlala** [comment]
Catcher won't catch async errors on debug. There is an issue raised: https://github.com/flutter/flutter/issues/48972

@prondzyn Please provide sample code, flutter doctor and your catcher version. You can also try running app in release mode. Your exception won't be handled be gesture and Catcher will be able to catch it.

**Comment by prondzyn** [comment]
@jhomlala so the errors catching behaves differently in debug and release modes? 🤕

**Comment by jhomlala** [comment]
Yeah, seems like Flutter framework "catches too much" in debug mode. To fix this issue in debug mode, you can always add try catch in your async mode like this:
```
try {
  ...
} catch (error,stackTrace) {
  Catcher.reportCheckedError(error, stackTrace);
}
```
This will report catched error to Catcher and he will proceed with this error.

**Comment by prondzyn** [comment]
Perfect!
