### ISSUE TITLE
Error Widget causes renderflex error when displaying inside a small widget.

### ISSUE THREAD

**Issue by GrahamDi** [jhomlala/catcher#80]
I implemented the error widget to replace the red-screen-of-death and normally it works fine. However, when an error occurs in a small display widget, such as a card being used as a grid tile, a renderflex error is generated and this error 'replaces' the original error (that caused Catcher to trigger) in the catcher report and stack dump so I cannot see what the true application error is.
If I remove the error widget and accept seeing the red screen in the gridtile then Catcher reports the correct application error. It appears then that the red screen handles any size widget and does not cause a renderflex.
Can the error widget be made to handle any size widget also?

I am using Catcher 0.3.2.

**Comment by jhomlala** [comment]
Fixed in Catcher 0.3.4

**Comment by GrahamDi** [comment]
Great stuff! Look forward to testing it tomorrow. Thanks for fixing it. Your package has helped me a huge amount in my beta test and gives me a lot of confidence for my go live.
