### ISSUE TITLE
Couldn't use report mode

### ISSUE THREAD

**Issue by visual-velocity** [jhomlala/catcher#89]
I'm facing this issue, i already test with custom navigator key and Catcher navigator key, Report will not generate.
Catcher | FINE] Using debug config
Catcher | FINE] Catcher configured successfully.
Setup localization lazily!
Catcher | WARNING] Couldn't use report mode because you didn't provide navigator key. Add navigator key to use this report mode.
ERROR: Não foi possivem oter informações da KEY

I used auto_route package inside my app. Can you suggest me why is this happening and showing this warning.

**Comment by jhomlala** [comment]
`Catcher | WARNING] Couldn't use report mode because you didn't provide navigator key. Add navigator key to use this report mode.`

You didn't provide navigator key to Catcher and you've used report mode that requires navigator key. https://github.com/jhomlala/catcher#adding-navigator-key

**Comment by visual-velocity** [comment]
@jhomlala  i have passed Catcher.navigatorKey inside Material app and i had also tested my application with Custom navigator key. I used auto_route package inside my app. Is it possible to get this issue due to use of auto_route package.

**Comment by jhomlala** [comment]
From my perspective, auto_route overides navigator key, so Catcher can't open new page. What you need to do is get actual key from auto_route and pass it to Catcher or use your navigator key in Catcher and auto_route.

**Comment by visual-velocity** [comment]
@jhomlala Thank you so much for your last suggestion. It's working. You helped in my production app.

**Comment by vaidikkamde** [comment]
@prasantco I am facing the same issue can you guide me through how you passed the navigatorKey from auto_route to the Catcher and also if you made your own report mode how did you approached that.
