### ISSUE TITLE
"FileHandler" doesn't work

### ISSUE THREAD

**Issue by YuuWoods** [jhomlala/catcher#93]
Hi jhomlala,
I tried to use "FileHandler" but it doesn't work.

flutter sdk v1.17.1
catcher 0.3.7

catcher-master/example/lib/file_example.dart

I tapped "Generate error" button.
But it doesn't give me a dialog, it gives me just a normal error. Catcher doesn't work.
```
E/flutter ( 7385): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Test exception
E/flutter ( 7385): #0      ChildWidget.generateError (package:catcher_example/file_example.dart:64:5)
E/flutter ( 7385): #1      ChildWidget.build.<anonymous closure> (package:catcher_example/file_example.dart:54:61)
E/flutter ( 7385): #2      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:779:19)
...Abbreviated below...
```
Original main() code:
```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  Directory externalDir = await getExternalStorageDirectory();

  String path = externalDir.path.toString() + "/log.txt";

  CatcherOptions debugOptions =
      CatcherOptions(DialogReportMode(), [FileHandler(File(path))]);
  CatcherOptions releaseOptions =
      CatcherOptions(DialogReportMode(), [FileHandler(File(path))]);

  Catcher(MyApp(), debugConfig: debugOptions, releaseConfig: releaseOptions);
}
```

So, I've commented out the code below.
```
WidgetsFlutterBinding.ensureInitialized();
Directory externalDir = await getExternalStorageDirectory();

String path = externalDir.path.toString() + "/log.txt";
```
And I have replaced
`FileHandler(File(path))`
with
`ConsoleHandler()`
Result:
```
void main() async {
//  WidgetsFlutterBinding.ensureInitialized();
//  Directory externalDir = await getExternalStorageDirectory();

//  String path = externalDir.path.toString() + "/log.txt";

  CatcherOptions debugOptions =
      CatcherOptions(DialogReportMode(), [ConsoleHandler()]);
  CatcherOptions releaseOptions =
      CatcherOptions(DialogReportMode(), [ConsoleHandler()]);

  Catcher(MyApp(), debugConfig: debugOptions, releaseConfig: releaseOptions);
}
```
Then,
I tapped "Generate error".
A dialog appears and the console shows an error made by the "catcher" as I expected.

However, when I uncommented the code below, 
`//  WidgetsFlutterBinding.ensureInitialized();`
Result:
```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
//  Directory externalDir = await getExternalStorageDirectory();

//  String path = externalDir.path.toString() + "/log.txt";

  CatcherOptions debugOptions =
      CatcherOptions(DialogReportMode(), [ConsoleHandler()]);
  CatcherOptions releaseOptions =
      CatcherOptions(DialogReportMode(), [ConsoleHandler()]);

  Catcher(MyApp(), debugConfig: debugOptions, releaseConfig: releaseOptions);
}
```
Then I tapped "Generate error".
I got the same result as the first time.

It would be very helpful if you could tell me how to make it work properly.

**Comment by jhomlala** [comment]
There's a bug in Flutter since 1.17.x. When you're using `WidgetsFlutterBinding.ensureInitialized();` it won't catch error in runZonedGuarded/runZoned block.
What you can do right now is specify file path manually:
```  String path = "/storage/emulated/0/log.txt";
  CatcherOptions debugOptions = CatcherOptions(
      DialogReportMode(), [FileHandler(File(path), printLogs: true)]);
  CatcherOptions releaseOptions =
      CatcherOptions(DialogReportMode(), [FileHandler(File(path))]);
```
I know it's not elegant way to fix this, but hope you'll be able to use file handler in your debug mode. I'll leave this issue open and watch for Flutter changes.

**Comment by YuuWoods** [comment]
Thank you so much for your reply.
I didn't know that at all.
Thank you for the tips.
Hopefully, Flutter will be fixed soon.

**Comment by votruk** [comment]
@jhomlala what about iOS devices? Are there any tricks available?

**Comment by jhomlala** [comment]
What about them? They should work same as android devices. I don't see any difference here and don't know any tips that can share with you :(
