### ISSUE TITLE
Attribute dateTime is wrong 

### ISSUE THREAD

**Issue by sweatfryash** [jhomlala/catcher#94]
Hello.
The dateTime output in the reportLog is eight hours different from my real time here,I think it's caused by different time zone.So how can I solve it without reduce eight hours,can I set the time zone?

**Comment by sweatfryash** [comment]
Catcher is working well,so I did not put the flutter doctor outputs or some code here,just a little problem.

**Comment by jhomlala** [comment]
Catcher calls DateTime.now() which is device time. So in report log you should see local time of your device. What's your timezone? Can you try run some tests with getting time with DateTime.now() and printing it in your console? What configuration are you using with Catcher?
