### ISSUE TITLE
Feature request: Firebase Handler

### ISSUE THREAD

**Issue by egorges** [jhomlala/catcher#96]
I'd like to send the error to Firebase Realtime.
It would be wonderful to use something like:
FirebaseHandler(
      child: DatabaseReference,
      enableDeviceParameters: true,
      enableStackTrace: true,
      enableCustomParameters: true,
      enableApplicationParameters: true,
      printLogs: true)

Thanks

**Comment by jhomlala** [comment]
I have no plans do it right now. I'm not sure that using firebase realtime database to catch errors is good choose. You should use firebase crashlytics to catch errors in your app. Anyway if you still want to use firebase realtime database, you can create your own handler. You need to extend `ReportHandler` class and implement it. Then you can pass it to Catcher.

**Comment by mikeesouth** [comment]
Is there an handler to use Firebase Crashlytics in conjunction with other handlers in Catcher? I want to log exceptions to two different services. Firebase Crashlytics is usually enabled using `FlutterError.onError = Crashlytics.instance.recordFlutterError;` but that will catch the exceptions globally and thus prevent catcher from handling it. It would be really nice to just have a CrashlyticsHandler() that I could add to the catcher handler list together with my other handlers.

I'm trying a custom handler now and calling Crashlytics.instance.recordFlutterError myself but it would be better to use an "official" handler.

Thanks for a great lib!

**Comment by jhomlala** [comment]
Added crashlytics handler in Catcher 0.3.15.

**Comment by dotdoom** [comment]
Would you like to add it to the platform support matrix? https://github.com/jhomlala/catcher/blob/master/platform_support.md
