### ISSUE TITLE
Update configuration for handlers

### ISSUE THREAD

**Issue by zm-sky** [jhomlala/catcher#97]
Hi there! I was wondering if there was a way to update CatcherOptions after app is up and running.
Currently using this on startup:

```

    CatcherOptions debugOptions = CatcherOptions(SilentReportMode(),
        [HttpHandler( HttpRequestType.post, Uri.parse('my-url',), headers: { 'Authorization': 'Bearer $myToken' } )]
    );
```
However, myToken may not be present at that given time if user was not previously logged in.
My use case is that i want to send a header with an userToken, so I can persist in my backend the user that experienced an error. After an user logs in, i want to update the headers that are sent when Catcher sends the error report

Is there a way to do this? Thank you in advance

**Comment by jhomlala** [comment]
* Update Catcher to version 0.3.8
* Check this example: https://github.com/jhomlala/catcher/blob/master/example/lib/http_handler_update_headers_example.dart

**Comment by zm-sky** [comment]
Awesome, thank you!
