### ISSUE TITLE
插件安装运行报错

### ISSUE THREAD

**Issue by 18487115313** [jhomlala/catcher#98]
`Compiler message:
/C:/flutter/.pub-cache/hosted/pub.flutter-io.cn/catcher-0.3.11/lib/core/catcher.dart:153:5: Error: The method 'runZonedGuarded' isn't defined for the class 'Catcher'.
 - 'Catcher' is from 'package:catcher/core/catcher.dart' ('/C:/flutter/.pub-cache/hosted/pub.flutter-io.cn/catcher-0.3.11/lib/core/catcher.dart').
Try correcting the name to the name of an existing method, or defining a method named 'runZonedGuarded'.
    runZonedGuarded<Future<void>>(() async {
    ^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'C:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 780

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s
Finished with error: Gradle task assembleDebug failed with exit code 1
`

**Comment by 18487115313** [comment]
core文件中 当前代码 : 
    runZonedGuarded<Future<void>>(() async {
      runApp(rootWidget);
    }, (dynamic error, StackTrace stackTrace) {
      _reportError(error, stackTrace);
    });
是否更改为:
    runZoned<Future<void>>(() async {
      runApp(rootWidget);
    }, onError: (error, stackTrace) {
      _reportError(error, stackTrace);         //上传异常日志
    });

**Comment by 18487115313** [comment]
看了下官方文档  需要升级到 1.17.0版本

**Comment by jhomlala** [comment]
Please write your issues in english next time.

Your issue has been fixed in latest version.
